import { existsSync, mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import type { Config } from "@react-router/dev/config";
import { sentryOnBuildEnd } from "@sentry/react-router";

// #AI-slop
// File is gitignored & generated by `mise client:prefetch-from-server`.
// Vite eagerly resolves the JSON import in `[slug].tsx` at dev-server start,
// so the file must exist by the time react-router-dev boots — create an empty
// stub if missing. e2e + production runs overwrite it with real data.
const prefetchPath = fileURLToPath(
  new URL("./graphql/prefetch/JobsLandingPages.json", import.meta.url),
);
if (!existsSync(prefetchPath)) {
  mkdirSync(fileURLToPath(new URL("./graphql/prefetch/", import.meta.url)), { recursive: true });
  writeFileSync(prefetchPath, '{ "jobs_landing_pages": [] }\n');
}

export default {
  ssr: false,
  appDirectory: "src",
  buildEnd: async (args) => {
    args.reactRouterConfig = {
      ...args.reactRouterConfig,
      /**
       * For Sentry source maps:
       * `sentry-cli sourcemaps upload <path>` strips <path> from artifact names and prefixes with ~/
       * build/client/ (not build/) -> ~/assets/foo.js matches served URLs.
       */
      buildDirectory: args.reactRouterConfig.buildDirectory + "/client",
    };
    await sentryOnBuildEnd(args);
  },
  // #AI-slop
  prerender: () => {
    if (!existsSync(prefetchPath)) {
      return [];
    }
    const data = JSON.parse(readFileSync(prefetchPath, "utf-8")) as {
      jobs_landing_pages?: { slug: string }[];
    };
    return data.jobs_landing_pages?.map((page) => `/${page.slug}`) ?? [];
  },
} satisfies Config;
