# Generated by Django 5.2.11 on 2026-02-20 06:21

import django.contrib.postgres.fields
import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0030_posttagcategory_posttag_categories"),
        ("users", "0002_alter_user_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalJob",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                (
                    "visibility",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("private", "Private"),
                            ("users_selected", "Users Selected"),
                            ("connections", "Connections"),
                            ("subscribers_paid", "Subscribers Paid"),
                            ("subscribers", "Subscribers"),
                            ("internal", "Internal"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("org", models.CharField(blank=True, max_length=512)),
                ("is_remote", models.BooleanField(blank=True, null=True)),
                ("is_remote_friendly", models.BooleanField(blank=True, null=True)),
                ("is_visa_sponsor", models.BooleanField(blank=True, null=True)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "country",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "city",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "url_external",
                    models.CharField(blank=True, max_length=1024, verbose_name="URL"),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical job",
                "verbose_name_plural": "historical jobs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="Job",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visibility",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("private", "Private"),
                            ("users_selected", "Users Selected"),
                            ("connections", "Connections"),
                            ("subscribers_paid", "Subscribers Paid"),
                            ("subscribers", "Subscribers"),
                            ("internal", "Internal"),
                            ("public", "Public"),
                        ],
                        default="private",
                        max_length=16,
                    ),
                ),
                ("title", models.CharField(max_length=512)),
                ("org", models.CharField(blank=True, max_length=512)),
                ("is_remote", models.BooleanField(blank=True, null=True)),
                ("is_remote_friendly", models.BooleanField(blank=True, null=True)),
                ("is_visa_sponsor", models.BooleanField(blank=True, null=True)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("salary_max", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "country",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "city",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=128),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "url_external",
                    models.CharField(blank=True, max_length=1024, verbose_name="URL"),
                ),
                ("posted_at", models.DateTimeField(blank=True, null=True)),
                ("closes_at", models.DateTimeField(blank=True, null=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "bookmarked_by_users",
                    models.ManyToManyField(
                        blank=True, related_name="jobs_bookmarked", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "tags_area",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"categories__name": "area"},
                        related_name="tags_job_area",
                        to="posts.posttag",
                    ),
                ),
                (
                    "tags_education",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"categories__name": "education"},
                        related_name="tags_job_education",
                        to="posts.posttag",
                    ),
                ),
                (
                    "tags_experience",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"categories__name": "experience"},
                        related_name="tags_job_experience",
                        to="posts.posttag",
                    ),
                ),
                (
                    "tags_skill",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"categories__name": "skill"},
                        related_name="tags_job_skill",
                        to="posts.posttag",
                    ),
                ),
                (
                    "tags_workload",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={"categories__name": "workload"},
                        related_name="tags_job_workload",
                        to="posts.posttag",
                    ),
                ),
                (
                    "visible_to_groups",
                    models.ManyToManyField(
                        blank=True, related_name="jobs_visible", to="users.userconnectiongroup"
                    ),
                ),
                (
                    "visible_to_users",
                    models.ManyToManyField(
                        blank=True, related_name="jobs_visible", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
