# Generated by Django 5.2.11 on 2026-02-26 01:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0001_initial"),
        ("orgs", "0002_alter_org_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="org_detail",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="orgs.org",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="org_detail",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="jobs",
                to="orgs.org",
            ),
        ),
    ]
