# Generated by Django 5.2.11 on 2026-02-27 03:15

import uuid

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0004_remove_historicaljob_org_detail_and_more"),
        ("orgs", "0004_org_logo"),
        ("posts", "0030_posttagcategory_posttag_categories"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="org",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="jobs", to="orgs.org"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalJobAlert",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("id_ext", models.UUIDField(default=uuid.uuid4)),
                ("email", models.EmailField(max_length=254)),
                ("is_orgs_highlighted", models.BooleanField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("jobs_clicked_count", models.PositiveIntegerField(default=0)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical job alert",
                "verbose_name_plural": "historical job alerts",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="JobAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id_ext", models.UUIDField(default=uuid.uuid4)),
                ("email", models.EmailField(max_length=254)),
                ("is_orgs_highlighted", models.BooleanField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("jobs_clicked_count", models.PositiveIntegerField(default=0)),
                ("jobs_clicked", models.ManyToManyField(blank=True, to="jobs.job")),
                (
                    "tags",
                    models.ManyToManyField(blank=True, related_name="tags", to="posts.posttag"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
