# Generated by Django 5.2.11 on 2026-02-27 23:13

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0005_alter_job_org_historicaljobalert_jobalert"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_remote",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_remote",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
