# Generated by Django 5.2.11 on 2026-02-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0006_historicaljobalert_is_remote_jobalert_is_remote"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="salary_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="salary_min",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
