# Generated by Django 5.2.11 on 2026-03-02 06:55

import django_extensions.db.fields
from django.db import migrations


def populate_slug_field(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    for job in Job.objects.all():
        job.save()


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0007_historicaljobalert_salary_min_jobalert_salary_min"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["title", "org__name"]
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from=["title", "org__name"]
            ),
        ),
        migrations.RunPython(populate_slug_field, migrations.RunPython.noop),
    ]
