# Generated by Django 5.2.11 on 2026-03-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_historicaljob_slug_job_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True, default=""),
        ),
    ]
