# Generated by Django 5.2.11 on 2026-03-08 06:18

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_historicaljob_slug_job_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlertLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_hash", models.CharField(max_length=128)),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "job",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="alert_logs",
                        to="jobs.job",
                    ),
                ),
                (
                    "job_alert",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="jobs.jobalert",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
