# Generated by Django 5.2.11 on 2026-03-06 11:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_historicaljob_slug_job_slug"),
    ]

    # #AI
    # Redundant: description is added by 0014_historicaljob_description_job_description
    operations = []
