# Generated by Django 5.2.11 on 2026-03-08 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0008_historicaljob_slug_job_slug"),
        ("posts", "0031_posttag_aliases_alter_posttagcategory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="city",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="country",
        ),
        migrations.RemoveField(
            model_name="job",
            name="city",
        ),
        migrations.RemoveField(
            model_name="job",
            name="country",
        ),
        migrations.AddField(
            model_name="job",
            name="tags_city",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"categories__name": "city"},
                related_name="tags_job_city",
                to="posts.posttag",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="tags_country",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"categories__name": "country"},
                related_name="tags_job_country",
                to="posts.posttag",
            ),
        ),
    ]
