# Generated by Django 5.2.11 on 2026-03-09 10:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0009_historicaljob_description_job_description"),
        ("jobs", "0009_jobalertlog"),
        ("jobs", "0009_remove_historicaljob_city_and_more"),
    ]

    operations = []
