# Generated by Django 5.2.11 on 2026-03-10 01:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_merge_20260309_1647"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="slug",
        ),
        migrations.AddField(
            model_name="jobalertlog",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="jobalertlog",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
