# Generated by Django 5.2.11 on 2026-03-10 05:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0011_remove_historicaljob_slug_jobalertlog_created_at_and_more"),
        ("orgs", "0004_org_logo"),
        ("posts", "0031_posttag_aliases_alter_posttagcategory_name"),
        ("users", "0002_alter_user_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="is_published",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="job",
            name="versions",
            field=models.ManyToManyField(blank=True, related_name="version_of", to="jobs.job"),
        ),
        migrations.AddConstraint(
            model_name="job",
            constraint=models.UniqueConstraint(
                fields=("slug", "is_published"), name="unique_job_slug_is_published"
            ),
        ),
    ]
