# Generated by Django 5.2.11 on 2026-03-10 18:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0012_historicaljob_is_published_job_is_published_and_more"),
        ("posts", "0032_alter_posttagcategory_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="is_visa_sponsor",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_visa_sponsor",
        ),
        migrations.AddField(
            model_name="job",
            name="tags_country_visa_sponsor",
            field=models.ManyToManyField(
                blank=True,
                help_text="Country PostTags where this job sponsors visas",
                related_name="visa_sponsor_jobs",
                to="posts.posttag",
            ),
        ),
    ]
