# Generated by Django 5.2.11 on 2026-03-10 23:33

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0013_remove_historicaljob_is_visa_sponsor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
