# Generated by Django 5.2.11 on 2026-03-11 10:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0010_merge_20260309_0308"),
        ("jobs", "0014_historicaljob_description_job_description"),
    ]

    operations = []
