# Generated by Django 5.2.11 on 2026-03-11 00:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0014_historicaljob_description_job_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="salary_max",
        ),
        migrations.RemoveField(
            model_name="job",
            name="salary_max",
        ),
    ]
