# Generated by Django 5.2.11 on 2026-03-11 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0015_remove_historicaljob_salary_max_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="salary_text",
            field=models.TextField(
                blank=True, help_text="Orgs can specify multiple ranges for multiple locations."
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="salary_text",
            field=models.TextField(
                blank=True, help_text="Orgs can specify multiple ranges for multiple locations."
            ),
        ),
    ]
