# Generated by Django 5.2.11 on 2026-03-13 02:03

import timezone_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0016_historicaljob_salary_text_job_salary_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="tz",
            field=timezone_field.fields.TimeZoneField(blank=True, default=""),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="tz",
            field=timezone_field.fields.TimeZoneField(blank=True, default=""),
        ),
    ]
