# Generated by Django 5.2.11 on 2026-03-13 09:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0015_merge_20260311_0330"),
        ("jobs", "0017_historicaljobalert_tz_jobalert_tz"),
    ]

    operations = []
