# Generated by Django 5.2.11 on 2026-03-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0017_historicaljobalert_tz_jobalert_tz"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("city", models.CharField(blank=True, max_length=255)),
                ("country", models.CharField(blank=True, max_length=255)),
                ("region", models.CharField(blank=True, max_length=255)),
                ("is_remote", models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name="job",
            name="locations",
            field=models.ManyToManyField(blank=True, to="jobs.joblocation"),
        ),
    ]
