# Generated by Django 5.2.11 on 2026-03-16 16:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0018_merge_20260313_0234"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
