# Generated by Django 5.2.11 on 2026-03-21 04:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0018_joblocation_job_locations"),
        ("jobs", "0019_alter_historicaljob_description_and_more"),
    ]

    operations = []
