# Generated by Django 5.2.11 on 2026-03-21 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0020_merge_20260320_2108"),
        ("sites", "0005_alter_siteconfig_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobFaqQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("question", models.CharField(max_length=512)),
                ("answer_md", models.TextField()),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="faq_questions",
                        to="sites.siteconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
    ]
