# Generated by Django 5.2.11 on 2026-03-21 04:08

from django.db import migrations

FAQ_ITEMS = [
    {
        "question": "How are roles selected for the board?",
        "answer_md": """Our goal is to feature promising roles working on the world's most important [global problems](https://probablygood.org/cause-areas/). To that end, we only include roles from organizations that we estimate to meet a meaningful bar for impact. We source organizations primarily through our own internal research, while also drawing on other signals for impact like recommendations from rigorous [charity evaluators](https://probablygood.org/core-concepts/effective-giving/#Charity_evaluators), support from impact-focused philanthropic foundations, and endorsements from experts. We also filter for different roles within organizations, only including opportunities from particularly impactful departments or teams where relevant.

That said, estimating impact is genuinely difficult, and we have real uncertainty about many of the organizations and roles we include. A role appearing on the board isn't a guarantee of impact, nor necessarily an endorsement of that organization's broader mission, practices, or culture. There are also likely strong opportunities we haven't come across yet or had the capacity to review. If you think a role or organization should or shouldn't be on the board, we'd love to [hear from you](https://probablygood.org/contact/).

Note that we include some roles primarily for the skills, experience, and connections they offer rather than their direct impact. These are assigned the [career capital](https://probablygood.org/core-concepts/career-capital/) label.""",
    },
    {
        "question": "What does the 'highlighted org' label mean?",
        "answer_md": """Roles marked with a *highlighted org* tag are roles within organizations that we've identified as doing particularly impactful or promising work. These organizations tend to have at least one of these characteristics: they receive recommendations from rigorous [charity evaluators](https://probablygood.org/core-concepts/effective-giving/#Charity_evaluators), have significant support from impact-focused foundations, operate in a [cause area](https://probablygood.org/cause-areas/) we consider particularly high priority, or use methods or interventions we believe to be [especially impactful](https://probablygood.org/core-concepts/method-efficacy/). That said, although we have more confidence in highlighted orgs than others on the board, impact is genuinely difficult to assess, and we still have uncertainties about potential impact within these orgs.""",
    },
    {
        "question": "What does the 'career capital' label mean?",
        "answer_md": """Career capital roles are opportunities we recommend primarily for the skills, experience, and connections they offer, rather than their direct impact. We think investing in the [right career capital](https://probablygood.org/core-concepts/career-capital/) early on is often the best path to long-term impact, positioning you for more influential roles later in your career.""",
    },
    {
        "question": "How can I list my vacancies on the board?",
        "answer_md": """If you're interested in getting your role featured on the board, you can fill out [this form](https://probablygood.org/contact/). Your submission will be reviewed by our team, and if we think you're a good fit for the board, we'll get back to you.

Note that Probably Good's job board is selective; we vet all organizations and roles we feature, and many aren't a good fit for the board. Before submitting, it's worth checking whether your organization works within the [cause areas](https://probablygood.org/cause-areas/) we prioritize, as we rarely list organizations outside of these. Working within these cause areas doesn't guarantee inclusion, but it's a strong signal that your organization might be a good fit.""",
    },
    {
        "question": "Where else can I find impactful jobs?",
        "answer_md": """We try to include as many impactful roles and organizations as we can, but there are likely strong opportunities not yet on the board. We recommend checking other job boards alongside ours, particularly if you're based in a non-English speaking region where our coverage is usually more limited. We've put together a [list of other relevant job boards](https://probablygood.org/resources/job-boards/) to help.""",
    },
    {
        "question": "How can I get in touch about the job board?",
        "answer_md": """If you have any feedback, questions, or suggestions of organizations to include on the job board, please [get in touch](https://probablygood.org/contact/)!""",
    },
    {
        "question": "Can you help me figure out what to do with my career?",
        "answer_md": """Yes! As a nonprofit that helps people build fulfilling and impactful careers, the job board is just one part of what we offer here at [Probably Good](https://probablygood.org/). If you're still figuring out your career direction, our [career guide](https://probablygood.org/career-guide/) is a good place to start; it walks you through the process of finding a high-impact career that fits your skills, interests, and values. We also have [loads of other content](https://probablygood.org/explore/), like [career profiles](https://probablygood.org/career-profiles/) that offer deeper dives into specific paths, [cause area](https://probablygood.org/cause-areas/) articles that highlight important global problems, and [interviews](https://probablygood.org/interviews/) with professionals who have had impactful careers.

If you're interested in more personalised support, we also offer an impact-focused [1:1 advising service](https://probablygood.org/advising/) to help you navigate the next stage of your career.

Note that we're funded by grants, so all our services are completely free; our only goal is to help you make a difference.""",
    },
]


def populate_faq(apps, schema_editor):
    SiteConfig = apps.get_model("sites", "SiteConfig")
    JobFaqQuestion = apps.get_model("jobs", "JobFaqQuestion")

    site, _ = SiteConfig.objects.get_or_create()

    for order, item in enumerate(FAQ_ITEMS, 1):
        JobFaqQuestion.objects.create(
            site=site,
            question=item["question"],
            answer_md=item["answer_md"],
            order=order,
        )


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0021_jobfaqquestion"),
        ("sites", "0005_alter_siteconfig_address_and_more"),
    ]

    operations = [
        migrations.RunPython(populate_faq, reverse_code=migrations.RunPython.noop),
    ]
