# Generated by Django 5.2.11 on 2026-03-21 04:10

import neuronhub.apps.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0022_populate_faq_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobfaqquestion",
            name="answer_md",
            field=neuronhub.apps.db.fields.MarkdownField(),
        ),
    ]
