# Generated by Django 5.2.11 on 2026-03-24 06:35

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0023_alter_jobfaqquestion_answer_md"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalert",
            name="jobs_notified_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="jobalertlog",
            name="jobs_notified_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
