# Generated by Django 5.2.11 on 2026-03-27 05:12

from django.db import migrations
from django.db import models

from neuronhub.apps.sites.models import url_with_utm_help_text


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0025_historicaljob_locations_historicaljob_tags_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="url_external_with_utm",
            field=models.CharField(
                blank=True,
                max_length=1024,
                help_text=url_with_utm_help_text,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="url_external_with_utm",
            field=models.CharField(
                blank=True,
                max_length=1024,
                help_text=url_with_utm_help_text,
            ),
        ),
    ]
