# Generated by Django 5.2.11 on 2026-03-30 02:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0026_historicaljob_url_external_with_utm_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob_tags_country",
            name="history",
        ),
        migrations.RemoveField(
            model_name="historicaljob_tags_country",
            name="job",
        ),
        migrations.RemoveField(
            model_name="historicaljob_tags_country",
            name="posttag",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="is_remote",
        ),
        migrations.RemoveField(
            model_name="historicaljob",
            name="is_remote_friendly",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_remote",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_remote_friendly",
        ),
        migrations.RemoveField(
            model_name="job",
            name="tags_city",
        ),
        migrations.RemoveField(
            model_name="job",
            name="tags_country",
        ),
        migrations.DeleteModel(
            name="HistoricalJob_tags_city",
        ),
        migrations.DeleteModel(
            name="HistoricalJob_tags_country",
        ),
    ]
