# Generated by Django 5.2.11 on 2026-03-30 04:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0027_remove_historicaljob_tags_country_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalert",
            name="locations",
            field=models.ManyToManyField(blank=True, to="jobs.joblocation"),
        ),
    ]
