# Generated by Django 5.2.11 on 2026-03-30 10:31

import django_extensions.db.fields
from django.db import migrations


def deduplicate_slugs(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    from django.db.models import Count

    dupes = Job.objects.values("slug").annotate(cnt=Count("id")).filter(cnt__gt=1)
    for entry in dupes:
        jobs = list(Job.objects.filter(slug=entry["slug"]).order_by("pk"))
        for i, job in enumerate(jobs[1:], start=2):
            job.slug = f"{job.slug}-{i}"
            job.save(update_fields=["slug"])


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0028_jobalert_locations"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="job",
            name="unique_job_slug_is_published",
        ),
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True,
                editable=False,
                max_length=512,
                populate_from=["title", "org__name"],
            ),
        ),
        migrations.RunPython(deduplicate_slugs, migrations.RunPython.noop),
    ]
