# Generated by Django 5.2.11 on 2026-03-30 13:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0028_jobalert_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_exclude_no_salary",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_exclude_no_salary",
            field=models.BooleanField(default=False),
        ),
    ]
