# Generated by Django 5.2.11 on 2026-03-30 23:55

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0029_remove_job_unique_job_slug_is_published_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="job",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, max_length=1024, populate_from=["title", "org__name"]
            ),
        ),
    ]
