# Generated by Django 5.2.11 on 2026-04-02 10:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0029_historicaljobalert_is_exclude_no_salary_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_exclude_career_capital",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_exclude_profit_for_good",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_exclude_career_capital",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_exclude_profit_for_good",
            field=models.BooleanField(default=False),
        ),
    ]
