# Generated by Django 5.2.11 on 2026-03-31 07:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0030_alter_job_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblocation",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="joblocation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
