# Generated by Django 5.2.11 on 2026-03-31 10:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0031_joblocation_created_at_joblocation_updated_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="jobalert",
            options={"get_latest_by": "pk"},
        ),
    ]
