# Generated by Django 5.2.11 on 2026-04-02 02:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0032_alter_jobalert_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_exclude_career_capital",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_exclude_no_salary",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_exclude_profit_for_good",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_exclude_career_capital",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_exclude_no_salary",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_exclude_profit_for_good",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
