# Generated by Django 5.2.11 on 2026-04-01 15:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0030_historicaljobalert_is_exclude_career_capital_and_more"),
        ("jobs", "0032_alter_jobalert_options"),
    ]

    operations = []
