# Generated by Django 5.2.11 on 2026-04-03 05:55

from django.db import migrations

import neuronhub.apps.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0033_historicaljobalert_is_exclude_career_capital_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="description",
            field=neuronhub.apps.db.fields.MarkdownField(
                blank=True, help_text="Use Markdown syntax."
            ),
        ),
    ]
