# Generated by Django 5.2.11 on 2026-04-04 01:17

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0034_alter_historicaljob_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="is_test_job",
            field=models.BooleanField(
                default=False,
                help_text="Excluded from Job Alerts outside of dev machines - by `DJANGO_ENV.is_dev()`. Indicates the Job was created by test_gen.py, eg in SiteConfig admin by 'Test Job Alert' button.",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_test_job",
            field=models.BooleanField(
                default=False,
                help_text="Excluded from Job Alerts outside of dev machines - by `DJANGO_ENV.is_dev()`. Indicates the Job was created by test_gen.py, eg in SiteConfig admin by 'Test Job Alert' button.",
            ),
        ),
    ]
