# Generated by Django 5.2.11 on 2026-04-06 03:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0035_historicaljob_is_test_job_job_is_test_job"),
    ]

    operations = [
        migrations.AddField(
            model_name="joblocation",
            name="type",
            field=models.CharField(
                choices=[("country", "Country"), ("city", "City"), ("remote", "Remote")],
                default="city",
                max_length=16,
            ),
        ),
    ]
