# Generated by Django 5.2.11 on 2026-04-06 03:44

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0037_backfill_joblocation_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joblocation",
            name="type",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("country", "Country"), ("city", "City"), ("remote", "Remote")],
                default="city",
                max_length=7,
            ),
        ),
    ]
