# Generated by Django 5.2.11 on 2026-04-06 11:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0039_backfill_country_locations"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljobalert",
            name="is_exclude_no_salary",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="jobalert",
            name="is_exclude_no_salary",
            field=models.BooleanField(default=False),
        ),
    ]
