# Generated by Django 5.2.11 on 2026-04-07 12:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0040_alter_historicaljobalert_is_exclude_career_capital_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_invalid_location",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_invalid_location",
            field=models.BooleanField(default=False),
        ),
    ]
