# Generated by Django 5.2.11 on 2026-04-09 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0041_historicaljobalert_is_invalid_location_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="source_ext",
            field=models.CharField(
                blank=True,
                help_text="External source identifier for URL filtering, eg 'AIM'.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="source_ext",
            field=models.CharField(
                blank=True,
                help_text="External source identifier for URL filtering, eg 'AIM'.",
                max_length=255,
            ),
        ),
    ]
