# Generated by Django 5.2.11 on 2026-04-09 21:43

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0043_mark_imported_alerts_jobs_as_seen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="source_ext",
            field=django_choices_field.fields.TextChoicesField(
                blank=True, choices=[("AIM", "Aim")], default=None, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="job",
            name="source_ext",
            field=django_choices_field.fields.TextChoicesField(
                blank=True, choices=[("AIM", "Aim")], default=None, max_length=3, null=True
            ),
        ),
    ]
