# Generated by Django 5.2.12 on 2026-04-11 02:44

from datetime import timedelta

from django.db import migrations
from django.db import models


def migrate_job_fk_to_m2m(apps, schema_editor):
    """
    Merged all JobAlertLogs within 10m into one JobAlertLog.

    #quality-22% #AI-slop, tested by many units.
    - had a bug of creating 2 duplicates from the merge because of a missing null check. Supposedly fixed.
    - Not fully reviewed code, esp the `[-1][0]` or `[1:]` trash code.
    """
    JobAlertLog = apps.get_model("jobs", "JobAlertLog")

    for log in JobAlertLog.objects.filter(job__isnull=False, job_alert__isnull=True):
        log.jobs.add(log.job_id)

    alert_logs = list(
        JobAlertLog.objects.filter(
            job__isnull=False,
            job_alert__isnull=False,
        ).order_by("job_alert_id", "sent_at")
    )

    log_groups = []
    for log in alert_logs:
        if log_groups and (
            log.job_alert_id == log_groups[-1][0].job_alert_id
            and (log.sent_at - log_groups[-1][0].sent_at) < timedelta(minutes=10)
        ):
            log_groups[-1].append(log)
        else:
            log_groups.append([log])

    for log_group in log_groups:
        log_leader = log_group[0]
        log_leader.jobs.set([log.job_id for log in log_group])
        if len(log_group) > 1:
            JobAlertLog.objects.filter(id__in=[log.id for log in log_group[1:]]).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0044_alter_historicaljob_source_ext_alter_job_source_ext"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalertlog",
            name="jobs",
            field=models.ManyToManyField(related_name="alert_logs", to="jobs.job"),
        ),
        migrations.RunPython(migrate_job_fk_to_m2m, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="jobalertlog",
            name="job",
        ),
        migrations.RemoveField(
            model_name="jobalertlog",
            name="jobs_notified_count",
        ),
    ]
