# Generated by Django 5.2.12 on 2026-04-12 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0045_remove_jobalertlog_job_and_more"),
        ("users", "0003_useranon"),
    ]

    operations = [
        migrations.AddField(
            model_name="jobalertlog",
            name="user_anon",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="alert_logs",
                to="users.useranon",
            ),
        ),
    ]
