# Generated by Django 5.2.12 on 2026-04-19 02:58

import django.db.models.deletion
import simple_history.models
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0046_jobalertlog_user_anon"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalJobAlert_jobs_clicked",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="jobs.historicaljobalert",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobs.job",
                    ),
                ),
                (
                    "jobalert",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobs.jobalert",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalJobAlert_jobs_clicked",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
