# Generated by Django 5.2.12 on 2026-04-19 05:30

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0047_historicaljobalert_jobs_clicked"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="is_removal",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="job",
            name="is_removal",
            field=models.BooleanField(default=False),
        ),
    ]
