# Generated by Django 5.2.12 on 2026-04-19 06:50

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0048_historicaljob_is_removal_job_is_removal"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaljob",
            name="is_removal",
        ),
        migrations.RemoveField(
            model_name="job",
            name="is_removal",
        ),
        migrations.AddField(
            model_name="historicaljob",
            name="is_pending_removal",
            field=models.BooleanField(
                default=False,
                help_text="If this Job was removed in Airtable, the removal will have this flag, and will wait an approval on /jobs/drafts from an admin. Only meaningful when is_published=False.",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_pending_removal",
            field=models.BooleanField(
                default=False,
                help_text="If this Job was removed in Airtable, the removal will have this flag, and will wait an approval on /jobs/drafts from an admin. Only meaningful when is_published=False.",
            ),
        ),
    ]
