# Generated by Django 5.2.12 on 2026-04-21 23:45

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0053_jobalert_jobs_clicked_to_arrayfield"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="is_duplicate_url_valid",
            field=models.BooleanField(
                default=False,
                help_text="Set from Airtable `Duplicate URL` - approved duplicates by data manager. Unapproved dup rows are deleted - only the latest `posted_at` is kept.",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="is_duplicate_url_valid",
            field=models.BooleanField(
                default=False,
                help_text="Set from Airtable `Duplicate URL` - approved duplicates by data manager. Unapproved dup rows are deleted - only the latest `posted_at` is kept.",
            ),
        ),
    ]
