# Generated by Django 5.2.12 on 2026-04-22 00:00
import datetime
from zoneinfo import ZoneInfo

from django.conf import settings
from django.db import migrations
from django.db import models


def update_invalid_job_history(apps, schema_editor):
    """
    Most (or all) Jobs without posted_at were created by db_stubs_repopulate.
    """

    # `Historical` is the magic prefix - as `Job.history` doesn't exist on apps.get_model("jobs", "Job").
    HistoricalJob = apps.get_model("jobs", "HistoricalJob")

    datetime_go_live = datetime.datetime(2026, 4, 7, tzinfo=ZoneInfo(settings.TIME_ZONE))
    HistoricalJob.objects.filter(posted_at=None).update(posted_at=datetime_go_live)


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0054_historicaljob_is_duplicate_url_valid_and_more"),
    ]

    operations = [
        migrations.RunPython(update_invalid_job_history, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="historicaljob",
            name="posted_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_at",
            field=models.DateTimeField(),
        ),
    ]
