# Generated by Django 5.2.12 on 2026-04-22 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0054_historicaljob_is_duplicate_url_valid_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaljob",
            name="posted_at",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="job",
            name="posted_at",
            field=models.DateTimeField(),
        ),
    ]
