# Generated by Django 5.2.12 on 2026-04-29 00:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0055_alter_historicaljob_posted_at_alter_job_posted_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="is_subscribe_to_newsletter",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user checked the newsletter checkbox. The API sub may fail, but this flag will be checked still.",
            ),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="is_subscribe_to_newsletter",
            field=models.BooleanField(
                default=False,
                help_text="Whether the user checked the newsletter checkbox. The API sub may fail, but this flag will be checked still.",
            ),
        ),
    ]
