# Generated by Django 5.2.13 on 2026-05-01 00:02

from django.db import migrations
from django.db import models
from django.db.models import F


def backfill_published_at(apps, schema_editor):
    Job = apps.get_model("jobs", "Job")
    Job.objects.filter(is_published=True, published_at__isnull=True).update(
        published_at=F("created_at")
    )


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0056_historicaljobalert_is_subscribe_to_newsletter_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljob",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when is_published flips to True. Used by Job Alerts to email about Jobs with published_at > JobAlert.created_at.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="published_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Set when is_published flips to True. Used by Job Alerts to email about Jobs with published_at > JobAlert.created_at.",
                null=True,
            ),
        ),
        migrations.RunPython(backfill_published_at, migrations.RunPython.noop),
    ]
