# Generated by Django 5.2.13 on 2026-05-11 04:13

import django.db.models.deletion
import django.utils.timezone
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0058_jobalertlog_job_slug_and_date_ids"),
        ("posts", "0035_rename_career_capital_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalJobsLandingPage",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("slug", models.SlugField(max_length=255)),
                (
                    "title",
                    models.CharField(
                        help_text="H1 + default <title>. Eg `Climate Change Jobs in France`.",
                        max_length=255,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, default="", max_length=512)),
                ("meta_image_url", models.URLField(blank=True, default="", max_length=512)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("is_orgs_highlighted", models.BooleanField(blank=True, null=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Note: prerender runs at build - changes only apply on next deploy.",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical jobs landing page",
                "verbose_name_plural": "historical jobs landing pages",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="JobsLandingPage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                (
                    "title",
                    models.CharField(
                        help_text="H1 + default <title>. Eg `Climate Change Jobs in France`.",
                        max_length=255,
                    ),
                ),
                ("meta_description", models.CharField(blank=True, default="", max_length=512)),
                ("meta_image_url", models.URLField(blank=True, default="", max_length=512)),
                ("salary_min", models.PositiveIntegerField(blank=True, null=True)),
                ("is_orgs_highlighted", models.BooleanField(blank=True, null=True)),
                (
                    "is_published",
                    models.BooleanField(
                        default=True,
                        help_text="Note: prerender runs at build - changes only apply on next deploy.",
                    ),
                ),
                ("locations", models.ManyToManyField(blank=True, to="jobs.joblocation")),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True,
                        limit_choices_to={
                            "categories__name__in": [
                                "area",
                                "skill",
                                "education",
                                "experience",
                                "workload",
                                "visa_sponsorship",
                            ]
                        },
                        related_name="landing_pages",
                        to="posts.posttag",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HistoricalJobsLandingPage_tags",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="jobs.historicaljobslandingpage",
                    ),
                ),
                (
                    "posttag",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="posts.posttag",
                    ),
                ),
                (
                    "jobslandingpage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobs.jobslandingpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalJobsLandingPage_tags",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name="HistoricalJobsLandingPage_locations",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("m2m_history_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "history",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="jobs.historicaljobslandingpage",
                    ),
                ),
                (
                    "joblocation",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobs.joblocation",
                    ),
                ),
                (
                    "jobslandingpage",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        db_tablespace="",
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="jobs.jobslandingpage",
                    ),
                ),
            ],
            options={
                "verbose_name": "HistoricalJobsLandingPage_locations",
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
