# Generated by Django 5.2.13 on 2026-05-14 05:25

import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0059_historicaljobslandingpage_jobslandingpage_and_more"),
        ("posts", "0035_rename_career_capital_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobslandingpage",
            name="source_ext",
            field=django_choices_field.fields.TextChoicesField(
                blank=True, choices=[("AIM", "Aim")], default=None, max_length=3, null=True
            ),
        ),
        migrations.AddField(
            model_name="jobslandingpage",
            name="source_ext",
            field=django_choices_field.fields.TextChoicesField(
                blank=True, choices=[("AIM", "Aim")], default=None, max_length=3, null=True
            ),
        ),
        migrations.AlterField(
            model_name="jobslandingpage",
            name="tags",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={
                    "categories__name__in": [
                        "skill",
                        "area",
                        "education",
                        "experience",
                        "workload",
                        "visa_sponsorship",
                    ]
                },
                related_name="landing_pages",
                to="posts.posttag",
            ),
        ),
    ]
