# Generated by Django 5.2.13 on 2026-05-14 23:56

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0060_historicaljobslandingpage_source_ext_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobslandingpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                max_length=512,
                help_text="If not set - the default from the homepage will be used for title/desc/image.",
            ),
        ),
        migrations.AddField(
            model_name="historicaljobslandingpage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="The Hero Header subtitle, eg `Curated high-impact jobs for people who want to make a difference.`",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="jobslandingpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                max_length=512,
                help_text="If not set - the default from the homepage will be used for title/desc/image.",
            ),
        ),
        migrations.AddField(
            model_name="jobslandingpage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="The Hero Header subtitle, eg `Curated high-impact jobs for people who want to make a difference.`",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljobslandingpage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="historicaljobslandingpage",
            name="meta_image_url",
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="historicaljobslandingpage",
            name="title",
            field=models.CharField(
                help_text="The Hero Header H1. Eg the homepage has `Find a job that's good, for you and for the world`.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="jobslandingpage",
            name="meta_description",
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="jobslandingpage",
            name="meta_image_url",
            field=models.URLField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name="jobslandingpage",
            name="title",
            field=models.CharField(
                help_text="The Hero Header H1. Eg the homepage has `Find a job that's good, for you and for the world`.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljobslandingpage",
            name="slug",
            field=models.SlugField(help_text="Root level slug", max_length=255),
        ),
        migrations.AlterField(
            model_name="jobslandingpage",
            name="slug",
            field=models.SlugField(help_text="Root level slug", max_length=255, unique=True),
        ),
    ]
