# Generated by Django 6.0.5 on 2026-07-04 11:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0062_rename_posted_at_to_created_at_in_airtable"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobalert",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicaljobalert",
            name="utm_content",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicaljobalert",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="historicaljobalert",
            name="utm_source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="utm_campaign",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="utm_content",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="utm_medium",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="jobalert",
            name="utm_source",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
