# Generated by Django 6.0.5 on 2026-07-25 16:50

import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0062_rename_posted_at_to_created_at_in_airtable"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaljobslandingpage",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="The page name the `{label}` templates fill in, eg `Impactful Climate Change Jobs`, `Impactful Jobs in London`. Must read as a plural noun - the H1 template appends `that are good for you...`.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="historicaljobslandingpage",
            name="org_type",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Nonprofit", "Nonprofit"),
                    ("For-Profit", "For Profit"),
                    ("Government", "Government"),
                    ("University", "University"),
                    ("International Institution", "International Institution"),
                    ("Think Tank", "Think Tank"),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="jobslandingpage",
            name="label",
            field=models.CharField(
                blank=True,
                help_text="The page name the `{label}` templates fill in, eg `Impactful Climate Change Jobs`, `Impactful Jobs in London`. Must read as a plural noun - the H1 template appends `that are good for you...`.",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="jobslandingpage",
            name="org_type",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Nonprofit", "Nonprofit"),
                    ("For-Profit", "For Profit"),
                    ("Government", "Government"),
                    ("University", "University"),
                    ("International Institution", "International Institution"),
                    ("Think Tank", "Think Tank"),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljobslandingpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional - if blank, it is generated from `SiteConfig.landing_meta_title_template`.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljobslandingpage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="The Hero Header subtitle. Optional - if blank, `SiteConfig.landing_subtitle_default` fills it.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="historicaljobslandingpage",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The Hero Header H1. Optional - if blank, it is generated from `SiteConfig.landing_title_template`.",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="jobslandingpage",
            name="meta_title",
            field=models.CharField(
                blank=True,
                help_text="Optional - if blank, it is generated from `SiteConfig.landing_meta_title_template`.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="jobslandingpage",
            name="subtitle",
            field=models.CharField(
                blank=True,
                help_text="The Hero Header subtitle. Optional - if blank, `SiteConfig.landing_subtitle_default` fills it.",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="jobslandingpage",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="The Hero Header H1. Optional - if blank, it is generated from `SiteConfig.landing_title_template`.",
                max_length=255,
            ),
        ),
    ]
