# Generated by Django 6.0.5 on 2026-08-05 07:55

import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
from django.db import migrations, models

_reasons = [
    ("I got a job! (Via this alert / this job board)", "none"),
    ("I got a job! (From another source)", "none"),
    ("Too many emails", "none"),
    ("I want to change alert filters", "none"),
    ("The alerts weren't what I expected", "none"),
    ("The roles were not relevant to me", "none"),
    ("Other", "required"),
]


def populate_unsubscribe_reasons(apps, schema_editor):
    SiteConfig = apps.get_model("sites", "SiteConfig")
    JobAlertUnsubscribeReason = apps.get_model("jobs", "JobAlertUnsubscribeReason")

    site, _ = SiteConfig.objects.get_or_create()

    for order, (label, comment_prompt) in enumerate(_reasons, 1):
        JobAlertUnsubscribeReason.objects.get_or_create(
            site=site,
            label=label,
            defaults={
                "comment_prompt": comment_prompt,
                "order": order,
            },
        )


class Migration(migrations.Migration):
    dependencies = [
        ("jobs", "0063_historicaljobalert_utm_campaign_and_more"),
        ("sites", "0018_migrate_job_alert_template_to_url_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="JobAlertUnsubscribeReason",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=256)),
                (
                    "comment_prompt",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("none", "No comment"),
                            ("optional", "Comment, optional"),
                            ("required", "Comment, required"),
                        ],
                        default="none",
                        max_length=8,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="unsubscribe_reasons",
                        to="sites.siteconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="JobAlertUnsubscribeFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("email", models.EmailField(max_length=254)),
                ("comment", models.TextField(blank=True)),
                (
                    "alert",
                    models.OneToOneField(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="unsubscribe_feedback",
                        to="jobs.jobalert",
                    ),
                ),
                (
                    "reasons",
                    models.ManyToManyField(
                        related_name="feedbacks", to="jobs.jobalertunsubscribereason"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        # Reverse is a noop - deleting the rows here makes Postgres refuse the DROP TABLE below
        # ("pending trigger events"), and the DROP removes them anyway.
        migrations.RunPython(
            populate_unsubscribe_reasons, reverse_code=migrations.RunPython.noop
        ),
    ]
