# Generated by Django 5.2.9 on 2026-02-10 05:20

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0002_remove_historicalprofile_is_bookmarked_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "match_score_by_llm",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Score",
                    ),
                ),
                ("match_reason_by_llm", models.TextField(blank=True)),
                (
                    "match_score",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="Score Adj",
                    ),
                ),
                (
                    "match_review",
                    models.TextField(
                        blank=True,
                        help_text="Usually why I scored it lower than LLM. Can be opinions, or pos feedback.",
                        verbose_name="Review",
                    ),
                ),
                ("match_batch_id", models.CharField(blank=True, db_index=True, max_length=64)),
                ("match_processed_at", models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name="profile",
            name="profiles_pr_match_s_4eee1d_idx",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="match_batch_id",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="match_processed_at",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="match_reason_by_llm",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="match_review_by_user",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="match_score_by_llm",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="match_score_by_user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="match_batch_id",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="match_processed_at",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="match_reason_by_llm",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="match_review_by_user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="match_score_by_llm",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="match_score_by_user",
        ),
        migrations.AlterField(
            model_name="historicalprofile",
            name="career_stage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Employed", "Employed"),
                        ("Self-employed", "Selfemployed"),
                        ("Not employed, looking", "Unemployedlooking"),
                        ("Working 0-5y", "Working0To5Y"),
                        ("Working 6-15y", "Working6To15Y"),
                        ("Working 15y+", "Working15Yplus"),
                        ("PhD student", "Phdstudent"),
                        ("Grad student", "Gradstudent"),
                        ("Undergrad", "Undergrad"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="career_stage",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(
                    choices=[
                        ("Employed", "Employed"),
                        ("Self-employed", "Selfemployed"),
                        ("Not employed, looking", "Unemployedlooking"),
                        ("Working 0-5y", "Working0To5Y"),
                        ("Working 6-15y", "Working6To15Y"),
                        ("Working 15y+", "Working15Yplus"),
                        ("PhD student", "Phdstudent"),
                        ("Grad student", "Gradstudent"),
                        ("Undergrad", "Undergrad"),
                    ],
                    max_length=50,
                ),
                blank=True,
                default=list,
                size=None,
            ),
        ),
        migrations.AddField(
            model_name="profilematch",
            name="profile",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="matches",
                to="profiles.profile",
            ),
        ),
        migrations.AddField(
            model_name="profilematch",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="profile_matches",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="profilematch",
            unique_together={("user", "profile")},
        ),
    ]
