# Generated by Django 5.2.9 on 2026-02-11 00:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0005_alter_profile_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprofile",
            name="match_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="profile",
            name="match_hash",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
    ]
