# Generated by Django 5.2.9 on 2026-02-11 00:52

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0029_drop_content_polite_from_imported_posts"),
        ("profiles", "0006_alter_historicalprofile_match_hash_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalprofile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="historicalprofile",
            name="skills",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="interests",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="skills",
        ),
        migrations.AddField(
            model_name="profile",
            name="interests",
            field=models.ManyToManyField(
                blank=True, related_name="profiles_interested", to="posts.posttag"
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="skills",
            field=models.ManyToManyField(
                blank=True, related_name="profiles_skilled", to="posts.posttag"
            ),
        ),
    ]
