# Generated by Django 5.2.9 on 2026-02-12 01:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0009_historicalprofilematch_created_at_and_more"),
        ("users", "0002_alter_user_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="visible_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="profiles_visible", to="users.userconnectiongroup"
            ),
        ),
    ]
