# Generated by Django 5.2.11 on 2026-02-13 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0010_profile_visible_to_groups"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="profilematch",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="profilematch",
            name="profile",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="match",
                to="profiles.profile",
            ),
        ),
    ]
