# Generated by Django 5.2.11 on 2026-02-13 09:12

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0012_alter_historicalprofile_recruitment_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprofile",
            name="content_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="profile",
            name="content_updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
