# Generated by Django 5.2.11 on 2026-02-13 21:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("profiles", "0013_historicalprofile_content_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalprofile",
            name="is_profile_custom",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_profile_custom",
            field=models.BooleanField(default=False),
        ),
    ]
