# Generated by Django 5.2.11 on 2026-02-15 11:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_historicalprofile_is_profile_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileinvite',
            name='username',
            field=models.CharField(default=datetime.datetime(2026, 2, 15, 11, 19, 30, 832733, tzinfo=datetime.timezone.utc), max_length=256),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='historicalprofilematch',
            name='match_batch_id',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='profilematch',
            name='match_batch_id',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
