name: neuronhub

services:
  postgres:
    image: postgres:17-alpine
    environment:
      POSTGRES_DB: neuronhub
      POSTGRES_USER: neuronhub
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username neuronhub"]
      interval: 5s
      timeout: 5s

volumes:
  postgres_data:
