[install-deps]
    depends = [
        "install-deps-server",
        "install-deps-client",
        "install-deps-pytest",
        "install-deps-pytest-chromium",
        "install-deps-claude-code",
    ]

[install-deps-server]
    dir = "server"
    run = "uv sync"

[install-deps-client]
    dir = "client"
    run = "bun install"

[install-deps-pytest]
    run = "uv tool install playwright"

[install-deps-pytest-chromium]
    run = "uv tool run playwright install chromium --with-deps"

[install-deps-claude-code]
    run = "npm install --global @anthropic-ai/claude-code @modelcontextprotocol/server-memory @modelcontextprotocol/server-sequential-thinking"
