#gui: true
dark-mode: true
watch-files: true
lint-cmd: ./.run/format.sh

editor: pycharm
auto-commits: false
cache-prompts: true # idk why false by default
analytics: false
gitignore: false
read:
  - docs/private/neuronhub/publish-later/code-style.md
  - docs/code-style-for-llm.md
  - docs/architecture.md
alias:
  - "smart:openrouter/google/gemini-2.5-pro-preview"
  - "cheap:openrouter/deepseek/deepseek-chat-v3-0324"
  - "fast:openrouter/deepseek/deepseek-chat-v3-0324"

# move clutter to /.aider/
env-file: .aider/.env
chat-history-file: .aider/.aider.chat.history.md
input-history-file: .aider/.aider.input.history
llm-history-file: .aider/.aider.llm.history
aiderignore: .aider/.aiderignore
