
services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: neuronhub
      POSTGRES_USER: neuronhub
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready --username neuronhub"]
      interval: 5s
      timeout: 5s

  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://neuronhub@postgres:5432/neuronhub
      ALLOWED_HOSTS: server,localhost
      SERVER_URL: http://server:8000
      CLIENT_URL: http://client:3000
    volumes:
      - .:/app
      - server_lib:/app/server/.venv
    ports:
      - "8000:8000"
    working_dir: /app/server
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/healthcheck/"]
      interval: 3s
      timeout: 7s

  client:
    build: ./client
    environment:
      VITE_API_URL: http://server:8000
    volumes:
      - .:/app
      - server_lib:/app/server/.venv
      - client_lib:/app/client/node_modules
      - ~/.claude:/root/.claude
    ports:
      - "3000:3000"
    working_dir: /app/client
    depends_on:
      server:
        condition: service_healthy

  test:
    build: ./server
    environment:
      DATABASE_URL: postgres://neuronhub@postgres:5432/neuronhub
      ALLOWED_HOSTS: server,localhost
      SERVER_URL: http://server:8000
      CLIENT_URL: http://client:3000
    volumes:
      - .:/app
      - server_lib:/app/server/.venv
      - client_lib:/app/client/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      server:
        condition: service_healthy
      client:
        condition: service_started
    command: ["bash", "-c", "cd /app/server && uv run pytest"]

volumes:
  postgres_data:
  server_lib:
  client_lib:
