redactions = ["*SECRET*", "*_API_KEY", "DATABASE_URL", "SENTRY_AUTH_TOKEN"]

[tools]
    "aqua:nushell/nushell" = "latest"

    uv = "latest"
    pnpm = "latest"
    biome = "latest"

	usage = "latest"
    rclone = "latest"
    killport = "latest"

    node = "25"

[settings]
	lockfile = true
    python.uv_venv_auto = true # let uv manage .venv/ <- should be default
	task.timings = false # noise for LLMs
    env_shell_expand = true # the default in v2026.7.0

    # Nushell for everything:
    unix_default_file_shell_args = "nu"
    unix_default_inline_shell_args = "nu --commands"
    use_file_shell_for_executable_tasks = true


[task_config]
    includes = [
        "devops/dependencies.mise.toml",
        "devops/db.mise.toml",
        "devops/docker.mise.toml",
        "devops/e2e.mise.toml",
        "devops/claude.mise.toml",
    ]

[env]
    _.file = { path = ".env.local" }

    # Global

    PROJECT_NAME = "{{ env.PROJECT_NAME | default(value = 'neuronhub') }}"
    VITE_PROJECT_NAME = "NeuronHub" # for FE HTML
    VITE_RELEASE_VERSION = "0.3.2.0-rc.9" # used in GitHub and Sentry

    DEPENDENCY_COOLDOWN_DAYS = 4

    SERVER_DOMAIN = "{{ env.SERVER_DOMAIN | default(value = 'localhost') }}"
    SERVER_PORT = "{{ env.SERVER_PORT | default(value = 8000) }}"
    SERVER_URL = "http://{{ env.SERVER_DOMAIN }}:{{ env.SERVER_PORT }}"

    CLIENT_DOMAIN = "{{ env.CLIENT_DOMAIN | default(value = 'localhost') }}"
    CLIENT_PORT = "{{ env.CLIENT_PORT | default(value = 3000) }}"
    CLIENT_URL = "http://{{ env.CLIENT_DOMAIN }}:{{ env.CLIENT_PORT }}"
    VITE_CLIENT_URL = "{{ env.CLIENT_URL }}"

    DOCS_DOMAIN = "{{ env.DOCS_DOMAIN | default(value = 'localhost') }}"
    DOCS_PORT = "{{ env.DOCS_PORT | default(value = 4000) }}"
    DOCS_URL = "http://{{ env.DOCS_DOMAIN }}:{{ env.DOCS_PORT }}"

    DB_USER = "{{ env.PROJECT_NAME }}"
    DB_NAME = "{{ env.PROJECT_NAME }}"
    DB_PASS = "{{ env.PROJECT_NAME }}"
    DB_PORT = "5432"
    DB_VER = "18" # for macos `psql-18`

    ADMIN_EMAIL = "support@{{ env.CLIENT_DOMAIN }}"
    VITE_ADMIN_EMAIL = "{{ env.ADMIN_EMAIL }}"

    GITHUB_PATH = "neuronhub-app/neuronhub"

    # Sentry

    SENTRY_ORG = "{{ env.PROJECT_NAME }}"
    SENTRY_DSN_FRONTEND = "https://97d9ce8ba2e7102f6ccfed17dd2e25aa@o4507887634284544.ingest.us.sentry.io/4510303776145408"
    SENTRY_DSN_BACKEND = "https://417078bf385cad9c59d41a020892e689@o4507887634284544.ingest.us.sentry.io/4510305221869575"
    VITE_RELEASE_NAME = "{{ env.PROJECT_NAME }}@{{ env.VITE_RELEASE_VERSION }}"

    # Algolia

    ALGOLIA_APPLICATION_ID = "${ALGOLIA_APPLICATION_ID:-VN4ESP6QTP}"
    ALGOLIA_SEARCH_API_KEY = "${ALGOLIA_SEARCH_API_KEY:-73e0fded909b86d55105cac456370c53}"
    ALGOLIA_API_KEY = "${ALGOLIA_API_KEY:-}"
    ALGOLIA_IS_ENABLED = "${ALGOLIA_IS_ENABLED:-false}"
    ALGOLIA_INDEX_POSTFIX_USER = "${USER:-'runner'}" # stop indexes clash between devs
    ALGOLIA_INDEX_DOCS = "${ALGOLIA_INDEX_DOCS:-docs_dev_{{ env.ALGOLIA_INDEX_POSTFIX_USER }}}"

    VITE_ALGOLIA_APPLICATION_ID = "${ALGOLIA_APPLICATION_ID}"
    VITE_ALGOLIA_SEARCH_API_KEY = "${ALGOLIA_SEARCH_API_KEY}"
    VITE_ALGOLIA_INDEX_DOCS = "${ALGOLIA_INDEX_DOCS}"

    # Analytics

    VITE_POSTHOG_TOKEN = "phc_NUVnraDugjykU3o5c3w6RFTJ2MK4u4G0iprxPaRjuN5"
    VITE_POSTHOG_HOST = "https://eu.i.posthog.com"

    # Dev

    SERVER_PORT_E2E = "{{ env.SERVER_PORT_E2E | default(value = 8001) }}"
    CLIENT_PORT_E2E = "{{ env.CLIENT_PORT_E2E | default(value = 3001) }}"
    DOCS_PORT_E2E = "{{ env.DOCS_PORT_E2E | default(value = 4001) }}"

    E2E_DB_NAME = "{{ env.E2E_DB_NAME | default(value = 'test_neuronhub_e2e') }}"

    S3_STORAGE_BUCKET_NAME = "media"
    S3_PORT = 8333

    IS_POSTGRES_EXTERNAL = "{{ env.IS_POSTGRES_EXTERNAL | default(value = env.CI | default(value = false)) }}"
    IS_POSTGRES_MACOS = "{{ env.IS_POSTGRES_EXTERNAL }}"
    POSTGRES_EXTERNAL_SHELL_MSG = "Skipping Postgres operation, as using non-Mise db (ie on GitHub CI)"

    # Claude

    CLAUDE_CODE_DISABLE_GIT_INSTRUCTIONS = 1

    CLAUDE_CODE_DISABLE_FEEDBACK_SURVEY = 1
    DISABLE_ERROR_REPORTING = 1
    DISABLE_BUG_COMMAND = 1

    CLAUDE_CODE_DISABLE_NONESSENTIAL_TRAFFIC = 1 # drops telemetry & npm updates


# Dev servers
# -----------------------------------------------------
[tasks.dev]
    depends = ["dev:server", "dev:client", "dev:db", "dev:s3"]

    [tasks."dev:server"]
        depends = "dev:db"
        dir = "server"
        run = "uv run manage.py runserver {{ env.SERVER_PORT }}"

    [tasks."dev:server-db-worker"]
        depends = "dev:db"
        dir = "server"
        run = "uv run manage.py db_worker"

    [tasks."dev:client"]
        depends = "dev:db"
        dir = "client"
        run = "pnpm exec react-router dev --host --port={{ env.CLIENT_PORT }}"
        env.VITE_SERVER_URL = "{{ env.SERVER_URL }}"

    [tasks."dev:s3"]
        dir = "server"
        run = """
            # rclone serve s3
            if $env.CI? != "true" {
                mkdir {{ env.S3_STORAGE_BUCKET_NAME }}
                try { rclone serve s3 . --addr 0.0.0.0:{{ env.S3_PORT }} }
            }
        """

    [tasks."dev:db"]
        dir = "devops"
        run = """
            # start postgres
            if $env.IS_POSTGRES_EXTERNAL == "true" {
                print $env.POSTGRES_EXTERNAL_SHELL_MSG
            } else if $env.IS_POSTGRES_MACOS == "true" {
                brew services start postgresql@{{ env.DB_VER}}
            } else {
                sudo -E docker compose up db --detach
            }
        """

    [tasks."dev:docs"]
        dir = "docs"
        run = "pnpm exec react-router dev"

    [tasks."dev:stop"]
        dir = "devops"
        run = [
            "killport --signal=SIGTERM {{ env.SERVER_PORT }} {{ env.CLIENT_PORT }} {{ env.S3_PORT }}",
            "sudo -E docker compose down db",
        ]


# Tests
# -----------------------------------------------------

[tasks.test]
    dir = "server"
    depends = "dev:db"
    run = """
        job spawn { mise dev:s3 }
        mise test:pytest
        mise test:e2e
    """

    [tasks."test:pytest"]
        dir = "server"
        depends = "dev:db"
        usage = '''
            arg "<args>" default=""
            flag "-a --include-all" default=#false
            flag "-m --markers <markers>" default="not slow_llm_api and not firebase_subscription"
        '''
        run = """
            job spawn { mise dev:s3 }

            let markers = if ($env.usage_include_all | into bool) { "" } else { $"-m ($env.usage_markers)" }
            let args = $"($env.usage_args)" | str replace "server/" ""

            uv run pytest $markers $args
        """
        alias = "pytest"
        env.DJANGO_ENV = "dev_test_unit"

    [tasks."test:pytest:all"]
        run = "mise pytest --include-all"

    [tasks."test:e2e"]
        dir = "client"
        alias = "e2e"
        run = "pnpm exec playwright test --config=e2e/playwright.config.ts"
        # duplicate $env with `dev:e2e:server`, as Playwright resets $env when it starts Mise from [[playwright.config.ts]]
        env.VITE_SERVER_URL = "http://localhost:{{ env.SERVER_PORT_E2E }}"
        env.E2E_DB_NAME = "{{ env.E2E_DB_NAME }}"
        env.IS_TASKS_BACKEND_IMMEDIATE = "false"

    [tasks."test:e2e:docs"]
        dir = "docs"
        alias = "e2e:docs"
        run = "pnpm exec playwright test --config=e2e/playwright.config.ts"


# Django
# -----------------------------------------------------

[tasks."django:migrate"]
    dir = "server"
    run = "uv run manage.py migrate"

[tasks."django:makemigrations"]
    dir = "server"
    run = "uv run manage.py makemigrations"

[tasks."django:db-stubs-repopulate"]
    dir = "server"
    run = "uv run manage.py db_stubs_repopulate"

[tasks."django:algolia-reindex"]
    dir = "server"
    run = [
        "mise django:algolia-reindex:post",
        "mise django:algolia-reindex:profile",
        "mise django:algolia-reindex:job",
        "mise algolia-reindex:docs",
    ]
[tasks."django:algolia-reindex:profile"]
    dir = "server"
    run = "uv run manage.py algolia_reindex_with_replicas --model=Profile"

[tasks."django:algolia-reindex:post"]
    dir = "server"
    run = "uv run manage.py algolia_reindex_with_replicas --model=Post"

[tasks."django:algolia-reindex:job"]
    dir = "server"
    run = "uv run manage.py algolia_reindex_with_replicas --model=Job"

[tasks."algolia-reindex:docs"]
    dir = "docs"
    run = "pnpm exec tsx scripts/algolia-index-docs.ts"


# typegen → format → lint
# -----------------------------------------------------

[tasks.typegen]
    depends = "typegen:server"
    run = [
        "mise typegen:client",
        "mise typegen:packages:chakra",
        "mise typegen:docs",
    ]
    description = "Strawberry → schema.graphql → TS enums; gql.tada Persisted Queries; @chakra-ui; etc"
    quiet = true

    [tasks."typegen:server"]
        dir = "server"
        run = "uv run manage.py export_schema neuronhub.graphql --path=../schema.graphql"
        sources = ["neuronhub/**/*.py"]
        outputs = ["../schema.graphql"]
        env.ALGOLIA_IS_ENABLED = "false"
    	quiet = true

    [tasks."typegen:client"]
        depends = [
            "typegen:client:graphql-codegen",
            "typegen:client:gql-tada",
            "typegen:client:chakra:*",
        ]
        quiet = true

    [tasks."typegen:client:graphql-codegen"]
        dir = "client"
        run = "pnpm exec graphql-codegen --errors-only --silent --config src/codegen.ts"
        sources = ["../schema.graphql"]
        quiet = true

    [tasks."typegen:client:gql-tada"]
        dir = "client"
        run = """
            let file = "../server/persisted-queries.json"

            pnpm exec gql-tada generate output
            pnpm exec gql-tada generate persisted --output $file
            open $file | sort | save --force $file
        """
        sources = ["src/**/*", "e2e/**/*"]
        silent = true # quiet doesn't work

    [tasks."typegen:client:chakra:neuron"]
        dir = "client"
        run = """
            let is_overrides_shared_node_modules = ($env.VITE_SITE? | default "") == "pg"; # see #123
            if not $is_overrides_shared_node_modules {
                # todo ! fix: still clashes with `pg`, ignoring for now
                pnpm exec chakra typegen src/theme/theme.ts | ignore
            }
        """
        sources = ["src/theme/**/*.ts"]
        silent = true # quiet doesn't work

    [tasks."typegen:client:chakra:pg"]
        dir = "client"
        run = "pnpm exec chakra typegen src/sites/pg/theme.ts"
        sources = ["src/sites/theme/**/*.ts", "src/sites/pg/theme.ts"]
        silent = true # quiet doesn't work

    [tasks."typegen:packages:chakra"]
        dir = "packages/shared"
        run = "mise typegen:chakra --dir=packages/shared/"
        sources = ["src/theme/**/*"]
        quiet = true

    [tasks."typegen:docs"]
        depends = [
            "typegen:docs:chakra",
            "typegen:docs:react-router",
        ]
        quiet = true

    [tasks."typegen:docs:chakra"]
        dir = "docs/"
        run = "mise typegen:chakra --dir=docs/"
        sources = ["src/theme/**/*"]
        quiet = true

    [tasks."typegen:docs:react-router"]
        dir = "docs"
        run = "pnpm exec react-router typegen"
        sources = ["src/**/*.mdx"]
        quiet = true

    [tasks."typegen:chakra"]
        usage = """
            flag "--dir <dir>"
        """
        # chakra modifies node_modules -> pnpm dedups @chakra-ui/react -> chakra overrides client/ or shared/ types -> fixed by --outdir
        run = """
            cd $env.usage_dir

            let output_dir = ".chakra/types"
            pnpm exec chakra typegen src/theme/theme.ts --outdir $output_dir

            # Generated .d.ts use rel imports `"../css.types"` -> breaks outside node_modules -> remap to #chakra-internal/ tsconfig path
            glob $"($output_dir)/*.d.ts" | each { |file|
                open $file --raw
                | str replace --all 'from "../' 'from "#chakra-internal/'
                | save --force $file
            }
        """
        silent = true

[tasks.format]
    depends = ["format:server", "format:biome"]
    quiet = true

    [tasks."format:server"]
        dir = "server"
        run = "uv run ruff format"
        sources = ["neuronhub/**/*.py"]
        quiet = true

    [tasks."format:biome"]
        run = "biome format --write"
        sources = [
            "packages/shared/src/**/*",
            "client/src/**/*",
            "client/e2e/**/*",
            "docs/src/**/*",
            "docs/e2e/**/*",
            "docs/scripts/**/*",
        ]
        quiet = true


[tasks.lint]
    depends = [
        "typegen",
        "format",
    ]
    depends_post = [
        "lint:server",
        "lint:client",
        "lint:docs",
        "lint:packages",
    ]
    quiet = true

    [tasks."lint:server"]
        dir = "server"
        run = "uv run mypy neuronhub"
        sources = ["neuronhub/**/*.py"]
        quiet = true

    [tasks."lint:biome"]
        run = [
            "biome lint --write --unsafe",
        ]
        sources = [
            "packages/shared/src/**/*",
            "client/src/**/*",
            "client/e2e/**/*",
            "docs/src/**/*",
            "docs/e2e/**/*",
        ]
        quiet = true

    [tasks."lint:client"]
        dir = "client/"
        run = "pnpm exec tsgo --noEmit"
        sources = ["src/**/*", "e2e/**/*", "tsconfig.json", "package.json"]
        quiet = true

    [tasks."lint:docs"]
        dir = "docs/"
        run = [
            "pnpm exec tsgo --noEmit",
            "pnpm exec tsx scripts/lint-mdx.ts",
        ]
        sources = ["src/**/*", "e2e/**/*", "scripts/**/*", "tsconfig.json", "package.json"]
        quiet = true

    [tasks."lint:packages"]
        dir = "packages/shared/"
        run = "pnpm exec tsgo --noEmit"
        sources = ["src/**/*", "package.json"]
        quiet = true
