# Generated by Django 5.1 on 2024-09-03 13:11

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0001_initial"),
        ("tools", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltoolreview",
            old_name="description",
            new_name="content",
        ),
        migrations.RenameField(
            model_name="toolalternative",
            old_name="is_positive_vote",
            new_name="is_vote_positive",
        ),
        migrations.RenameField(
            model_name="toolreview",
            old_name="description",
            new_name="content",
        ),
        migrations.RemoveField(
            model_name="historicaltool",
            name="github_stars",
        ),
        migrations.RemoveField(
            model_name="historicaltoolreview",
            name="org",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="github_stars",
        ),
        migrations.RemoveField(
            model_name="toolreview",
            name="org",
        ),
        migrations.RemoveField(
            model_name="tooltag",
            name="parent",
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="slug",
            field=models.SlugField(default="", max_length=511),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="historicaltoolreview",
            name="content_personal",
            field=models.TextField(blank=True, help_text="Visible only to the user"),
        ),
        migrations.AddField(
            model_name="tool",
            name="slug",
            field=models.SlugField(default="", max_length=511, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="toolreview",
            name="content_personal",
            field=models.TextField(blank=True, help_text="Visible only to the user"),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="orgs",
            field=models.ManyToManyField(related_name="tools", to="orgs.org"),
        ),
        migrations.AddField(
            model_name="tooltag",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="tooltag",
            name="tag_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tags_children",
                to="tools.tooltag",
            ),
        ),
        migrations.CreateModel(
            name="ToolStatsGithub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("stars", models.IntegerField()),
                ("kloc", models.IntegerField(blank=True, null=True)),
                ("forks", models.IntegerField(blank=True, null=True)),
                ("watchers", models.IntegerField(blank=True, null=True)),
                ("issues", models.IntegerField(blank=True, null=True)),
                ("pull_requests", models.IntegerField(blank=True, null=True)),
                (
                    "tool",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stats_github",
                        to="tools.tool",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
