# Generated by Django 5.1 on 2024-09-03 18:02

import django.core.validators
import django_extensions.db.fields
from django.db import migrations
from django.db import models

import neuronhub.apps.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0002_rename_description_historicaltoolreview_content_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltool",
            name="website_url",
        ),
        migrations.RemoveField(
            model_name="tool",
            name="website_url",
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="domain",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[django.core.validators.DomainNameValidator],
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="domain",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[django.core.validators.DomainNameValidator],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltool",
            name="description",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicaltool",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name"
            ),
        ),
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="content",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="content_personal",
            field=neuronhub.apps.db.fields.MarkdownField(
                blank=True, help_text="Visible only to the user"
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="description",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name="tool",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="content",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="content_personal",
            field=neuronhub.apps.db.fields.MarkdownField(
                blank=True, help_text="Visible only to the user"
            ),
        ),
    ]
