# Generated by Django 5.1 on 2024-09-03 18:14

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tools", "0003_remove_historicaltool_website_url_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltool",
            name="domain",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    django.core.validators.DomainNameValidator(accept_idna=False)
                ],
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="domain",
            field=models.CharField(
                blank=True,
                max_length=255,
                validators=[
                    django.core.validators.DomainNameValidator(accept_idna=False)
                ],
            ),
        ),
        migrations.CreateModel(
            name="ToolTagVote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_vote_positive", models.BooleanField()),
                (
                    "tag",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.tooltag"
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="tools.tool"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
