# Generated by Django 5.1 on 2024-09-26 07:35

import neuronhub.apps.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0002_alter_org_domain_alter_org_slug'),
        ('tools', '0004_alter_historicaltool_domain_alter_tool_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicaltoolreview',
            old_name='content_personal',
            new_name='content_private',
        ),
        migrations.RenameField(
            model_name='historicaltoolreview',
            old_name='is_published',
            new_name='is_private',
        ),
        migrations.RenameField(
            model_name='toolreview',
            old_name='content_personal',
            new_name='content_private',
        ),
        migrations.RenameField(
            model_name='toolreview',
            old_name='is_published',
            new_name='is_private',
        ),
        migrations.AddField(
            model_name='historicaltoolreview',
            name='rating_custom',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolreview',
            name='rating_custom',
            field=models.JSONField(blank=True, default={}),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tooltagvote',
            name='comment',
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='toolreview',
            name='orgs',
            field=models.ManyToManyField(blank=True, related_name='tools', to='orgs.org'),
        ),
    ]
