# Generated by Django 5.1 on 2024-09-26 07:36

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0005_rename_content_personal_historicaltoolreview_content_private_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="rating_custom",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="rating_custom",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
