# Generated by Django 5.1 on 2024-09-27 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0006_alter_historicaltoolreview_rating_custom_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='toolreview',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='reviews', to='tools.tooltag'),
        ),
        migrations.AlterUniqueTogether(
            name='tooltag',
            unique_together={('tag_parent', 'name')},
        ),
    ]
