# Generated by Django 5.1 on 2024-09-27 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0007_toolreview_tags_alter_tooltag_unique_together"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltoolreview",
            old_name="user",
            new_name="author",
        ),
        migrations.RenameField(
            model_name="toolreview",
            old_name="user",
            new_name="author",
        ),
    ]
