# Generated by Django 5.1 on 2024-09-27 06:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0008_rename_user_historicaltoolreview_author_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tooltagvote",
            old_name="user",
            new_name="author",
        ),
    ]
