# Generated by Django 5.1 on 2025-01-02 00:22

import django.core.validators
import django.db.models.deletion
import neuronhub.apps.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0009_rename_user_tooltagvote_author'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltoolreview',
            name='is_review_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicaltoolreview',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='is_review_later',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='source',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='tooltagvote',
            name='is_vote_positive',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ToolTagRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_rating', to=settings.AUTH_USER_MODEL)),
                ('tag_parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tags_children', to='tools.tooltagrating')),
                ('tools', models.ManyToManyField(blank=True, related_name='tags_rating', to='tools.tool')),
            ],
            options={
                'unique_together': {('tag_parent', 'name')},
            },
        ),
        migrations.CreateModel(
            name='ToolTagVoteRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_vote_positive', models.BooleanField()),
                ('comment', neuronhub.apps.db.fields.MarkdownField(blank=True)),
                ('rating', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tooltagrating')),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tools.tool')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
