# Generated by Django 5.1 on 2025-01-04 03:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0010_historicaltoolreview_is_review_later_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tooltagvoterating',
            name='tag',
        ),
        migrations.RemoveField(
            model_name='tooltagvoterating',
            name='author',
        ),
        migrations.RemoveField(
            model_name='tooltagvoterating',
            name='tool',
        ),
        migrations.DeleteModel(
            name='ToolTagRating',
        ),
        migrations.DeleteModel(
            name='ToolTagVoteRating',
        ),
    ]
