# Generated by Django 5.1 on 2025-01-04 08:10

import django_choices_field.fields
from django.db import migrations

import neuronhub.apps.posts.models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0011_remove_tooltagvoterating_tag_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltoolreview",
            name="usage_status",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("using", "Using"),
                    ("used", "Used"),
                    ("want_to_use", "Want to use"),
                    ("interested", "Interested"),
                    ("not_interested", "Not interested"),
                ],
                choices_enum=neuronhub.apps.posts.models.UsageStatus,
                default=None,
                max_length=14,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="usage_status",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("using", "Using"),
                    ("used", "Used"),
                    ("want_to_use", "Want to use"),
                    ("interested", "Interested"),
                    ("not_interested", "Not interested"),
                ],
                choices_enum=neuronhub.apps.posts.models.UsageStatus,
                default=None,
                max_length=14,
                null=True,
            ),
        ),
    ]
