# Generated by Django 5.1 on 2025-01-08 00:21

import django_choices_field.fields
import neuronhub.apps.tools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0012_historicaltoolreview_usage_status_and_more'),
        ('users', '0003_user_avatar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltoolreview',
            name='importance',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('extra_low', 'Extra Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], choices_enum=neuronhub.apps.tools.models.Importance, default=None, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='historicaltoolreview',
            name='visibility',
            field=django_choices_field.fields.TextChoicesField(choices=[('private', 'Private'), ('connection_groups', 'Connection Groups'), ('connections', 'Connections'), ('internal', 'Internal'), ('public', 'Public')], choices_enum=neuronhub.apps.tools.models.Visibility, default='private', max_length=17),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='importance',
            field=django_choices_field.fields.TextChoicesField(blank=True, choices=[('extra_low', 'Extra Low'), ('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], choices_enum=neuronhub.apps.tools.models.Importance, default=None, max_length=9, null=True),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='recommended_to_groups',
            field=models.ManyToManyField(blank=True, related_name='tools_recommended', to='users.userconnectiongroup'),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='recommended_to_users',
            field=models.ManyToManyField(blank=True, related_name='tools_recommended', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='visibility',
            field=django_choices_field.fields.TextChoicesField(choices=[('private', 'Private'), ('connection_groups', 'Connection Groups'), ('connections', 'Connections'), ('internal', 'Internal'), ('public', 'Public')], choices_enum=neuronhub.apps.tools.models.Visibility, default='private', max_length=17),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='visible_to_groups',
            field=models.ManyToManyField(blank=True, related_name='tools_visible', to='users.userconnectiongroup'),
        ),
        migrations.AddField(
            model_name='toolreview',
            name='visible_to_users',
            field=models.ManyToManyField(blank=True, related_name='tools_visible', to=settings.AUTH_USER_MODEL),
        ),
    ]
