# Generated by Django 5.1 on 2025-01-12 02:43

import neuronhub.apps.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0014_alter_historicaltoolreview_rating_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toolalternative',
            old_name='user',
            new_name='author',
        ),
        migrations.AddField(
            model_name='toolalternative',
            name='comment',
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name='toolalternative',
            name='is_vote_positive',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
