# Generated by Django 5.1 on 2025-01-12 02:43

from django.db import migrations
from django.db import models

import neuronhub.apps.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0014_alter_historicaltoolreview_rating_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toolalternative",
            old_name="user",
            new_name="author",
        ),
        migrations.AddField(
            model_name="toolalternative",
            name="comment",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name="toolalternative",
            name="is_vote_positive",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
