# Generated by Django 5.1 on 2025-01-12 02:52

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0015_rename_user_toolalternative_author_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tool",
            unique_together={("name", "domain")},
        ),
    ]
