# Generated by Django 5.1 on 2025-01-12 04:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0016_alter_tool_unique_together'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='historicaltoolreview',
            name='type',
            field=models.CharField(default='', help_text='Program, Link, Article, etc', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toolreview',
            name='type',
            field=models.CharField(default='Program', help_text='Program, Link, Article, etc', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='tooltagvote',
            unique_together={('tool', 'tag', 'author')},
        ),
    ]
