# Generated by Django 5.1 on 2025-01-12 04:21

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0017_historicaltoolreview_type_toolreview_type_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltoolreview",
            name="type",
        ),
        migrations.RemoveField(
            model_name="toolreview",
            name="type",
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="type",
            field=models.CharField(
                default="Program", help_text="Program, Link, Article, etc", max_length=255
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="tool",
            name="type",
            field=models.CharField(
                default="Program", help_text="Program, Link, Article, etc", max_length=255
            ),
            preserve_default=False,
        ),
    ]
