# Generated by Django 5.2b1 on 2025-03-17 20:55

import django.core.validators
import django.db.models.deletion
import django_choices_field.fields
import django_countries.fields
import django_extensions.db.fields
import neuronhub.apps.db.fields
import neuronhub.apps.tools.models
import simple_history.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0018_remove_historicaltoolreview_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=511)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("description", neuronhub.apps.db.fields.MarkdownField(blank=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[
                            django.core.validators.DomainNameValidator(accept_idna=False)
                        ],
                    ),
                ),
                ("country", django_countries.fields.CountryField(blank=True, max_length=2)),
                ("is_single_product", models.BooleanField(default=False)),
                ("crunchbase_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CompanyOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="historicaltool",
            name="domain",
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="historicaltoolreview",
            name="rating_trust_privacy",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="rating_trust_privacy",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="importance",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("extra_low", "Extra Low"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("extra_high", "Extra High"),
                ],
                choices_enum=neuronhub.apps.tools.models.Importance,
                default=None,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="importance",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("extra_low", "Extra Low"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                    ("extra_high", "Extra High"),
                ],
                choices_enum=neuronhub.apps.tools.models.Importance,
                default=None,
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tool",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="company",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="tools.company",
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="tools.company",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tool",
            unique_together={("name", "company")},
        ),
        migrations.AddField(
            model_name="company",
            name="ownership",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tools.companyownership"
            ),
        ),
        migrations.CreateModel(
            name="HistoricalCompany",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(blank=True, editable=False)),
                ("updated_at", models.DateTimeField(blank=True, editable=False)),
                ("name", models.CharField(max_length=511)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name"
                    ),
                ),
                ("description", neuronhub.apps.db.fields.MarkdownField(blank=True)),
                (
                    "domain",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[
                            django.core.validators.DomainNameValidator(accept_idna=False)
                        ],
                    ),
                ),
                ("country", django_countries.fields.CountryField(blank=True, max_length=2)),
                ("is_single_product", models.BooleanField(default=False)),
                ("crunchbase_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ownership",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="tools.companyownership",
                    ),
                ),
            ],
            options={
                "verbose_name": "historical company",
                "verbose_name_plural": "historical companys",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.RemoveField(
            model_name="tool",
            name="domain",
        ),
    ]
