# Generated by Django 5.2b1 on 2025-03-24 05:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0020_alter_tooltag_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="historicaltoolreview",
            old_name="rating_trust_privacy",
            new_name="rating_trust",
        ),
        migrations.RenameField(
            model_name="toolreview",
            old_name="rating_trust_privacy",
            new_name="rating_trust",
        ),
    ]
