# Generated by Django 5.2b1 on 2025-03-24 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0021_rename_rating_trust_privacy_historicaltoolreview_rating_trust_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tooltag",
            name="tools",
        ),
        migrations.AddField(
            model_name="tool",
            name="tools",
            field=models.ManyToManyField(
                blank=True, related_name="tags", related_query_name="tag", to="tools.tooltag"
            ),
        ),
        migrations.AlterField(
            model_name="tooltagvote",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="tools.tool",
            ),
        ),
    ]
