# Generated by Django 5.2b1 on 2025-03-24 21:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0022_remove_tooltag_tools_tool_tools_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="tool",
            name="tools",
        ),
        migrations.AddField(
            model_name="tool",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="tools", related_query_name="tool", to="tools.tooltag"
            ),
        ),
    ]
