# Generated by Django 5.2b1 on 2025-03-24 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0023_remove_tool_tools_tool_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooltagvote",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="tools.tooltag",
            ),
        ),
    ]
