# Generated by Django 5.2b1 on 2025-04-02 23:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0025_alter_toolalternative_author"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toolreview",
            old_name="tags",
            new_name="tool_tags",
        ),
        migrations.AddField(
            model_name="historicaltoolreview",
            name="experience_hours",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="experience_hours",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.RemoveField(
            model_name="toolreview",
            name="importance",
        ),
        migrations.AddField(
            model_name="toolreview",
            name="importance",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name="ToolReviewTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("is_vote_positive", models.BooleanField(blank=True, null=True)),
                (
                    "review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tags",
                        to="tools.toolreview",
                    ),
                ),
            ],
            options={
                "unique_together": {("review", "name")},
            },
        ),
    ]
