# Generated by Django 5.2b1 on 2025-04-03 00:48

import django.db.models.deletion
import django_choices_field.fields
import neuronhub.apps.tools.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0026_rename_tags_toolreview_tool_tags_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="company",
            name="ownership",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tools.companyownership",
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tools.company",
            ),
        ),
        migrations.AlterField(
            model_name="toolalternative",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="tool",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="tools.tool"
            ),
        ),
        migrations.AlterField(
            model_name="toolreviewtag",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("value", "Value"),
                    ("ease_of_use", "Ease of use"),
                    ("a_must", "A must"),
                    ("expectations", "Expectations"),
                    ("maturity", "Maturity"),
                    ("controversial", "Controversial"),
                    ("privacy", "Privacy"),
                    ("open_source", "Open Source"),
                    ("quality", "Quality"),
                    ("changed_my_mind", "Changed my mind"),
                    ("read_fully", "Read fully"),
                ],
                choices_enum=neuronhub.apps.tools.models.ReviewTagName,
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="tooltag",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="tooltag",
            name="tag_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tags_children",
                to="tools.tooltag",
            ),
        ),
        migrations.AlterField(
            model_name="tooltagvote",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
