# Generated by Django 5.2b1 on 2025-04-03 01:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0027_alter_company_ownership_alter_tool_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltoolreview",
            name="rating_custom",
        ),
        migrations.RemoveField(
            model_name="historicaltoolreview",
            name="rating_trust",
        ),
        migrations.RemoveField(
            model_name="toolreview",
            name="rating_custom",
        ),
        migrations.RemoveField(
            model_name="toolreview",
            name="rating_trust",
        ),
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="experience_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="importance",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="experience_hours",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="rating",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
