# Generated by Django 5.2b1 on 2025-04-03 19:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0028_remove_historicaltoolreview_rating_custom_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tooltag",
            name="is_important",
            field=models.BooleanField(default=False),
        ),
    ]
