# Generated by Django 5.2b1 on 2025-04-03 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0029_tooltag_is_important"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tooltag",
            name="is_important",
            field=models.BooleanField(
                default=False,
                help_text="An important Tag is highly informative of its Tool - it's shown before all others and displays an icon",
            ),
        ),
    ]
