# Generated by Django 5.2b1 on 2025-04-03 20:32

import neuronhub.apps.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0030_alter_tooltag_is_important"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicaltoolreview",
            name="content_cons",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="historicaltoolreview",
            name="content_pros",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="content_cons",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="content_pros",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
    ]
