# Generated by Django 5.2b1 on 2025-04-07 00:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0031_historicaltoolreview_content_cons_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="reviewed_at",
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
