# Generated by Django 5.2b1 on 2025-04-07 22:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0032_alter_historicaltoolreview_reviewed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="toolreview",
            name="users_favorite",
            field=models.ManyToManyField(
                blank=True, related_name="tools_favorite", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="users_read_later",
            field=models.ManyToManyField(
                blank=True, related_name="tools_read_later", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
