# Generated by Django 5.2b1 on 2025-04-07 22:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0033_toolreview_users_favorite_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolreview",
            name="users_favorite",
        ),
        migrations.RemoveField(
            model_name="toolreview",
            name="users_read_later",
        ),
        migrations.AddField(
            model_name="toolreview",
            name="reviews_read_later",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_read_later", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="users_library",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_library", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="toolreview",
            name="users_starred",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_starred", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
