# Generated by Django 5.2b1 on 2025-04-08 00:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0034_remove_toolreview_users_favorite_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="toolreview",
            old_name="reviews_read_later",
            new_name="users_read_later",
        ),
    ]
