# Generated by Django 5.2b1 on 2025-04-14 19:50

import django_choices_field.fields
import neuronhub.apps.anonymizer.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0038_alter_toolreviewvote_author"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="visibility",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("private", "Private"),
                    ("users_selected", "Users Selected"),
                    ("connection_groups_selected", "Connection Groups Selected"),
                    ("connections", "Connections"),
                    ("subscribers_paid", "Subscribers Paid"),
                    ("subscribers", "Subscribers"),
                    ("internal", "Internal"),
                    ("public", "Public"),
                ],
                choices_enum=neuronhub.apps.anonymizer.fields.Visibility,
                default="private",
                max_length=26,
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="visibility",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("private", "Private"),
                    ("users_selected", "Users Selected"),
                    ("connection_groups_selected", "Connection Groups Selected"),
                    ("connections", "Connections"),
                    ("subscribers_paid", "Subscribers Paid"),
                    ("subscribers", "Subscribers"),
                    ("internal", "Internal"),
                    ("public", "Public"),
                ],
                choices_enum=neuronhub.apps.anonymizer.fields.Visibility,
                default="private",
                max_length=26,
            ),
        ),
    ]
