# Generated by Django 5.2 on 2025-04-22 22:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0039_alter_historicaltoolreview_visibility_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltoolreview",
            name="reviewed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="reviewed_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
