# Generated by Django 5.2 on 2025-04-23 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0040_alter_historicaltoolreview_reviewed_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="tool",
            name="users_library",
            field=models.ManyToManyField(
                blank=True, related_name="library_tools", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="users_read_later",
            field=models.ManyToManyField(
                blank=True, related_name="read_later_tools", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="users_library",
            field=models.ManyToManyField(
                blank=True, related_name="library_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="users_read_later",
            field=models.ManyToManyField(
                blank=True, related_name="read_later_reviews", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
