# Generated by Django 5.2 on 2025-04-23 04:20

import django.db.models.deletion
import django_choices_field.fields
import neuronhub.apps.anonymizer.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tools", "0041_tool_users_library_tool_users_read_later_and_more"),
        ("users", "0006_user_id_uuid_alter_user_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="toolreview",
            name="orgs",
        ),
        migrations.RemoveField(
            model_name="toolreview",
            name="tool_tags",
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="author",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="historicaltool",
            name="visibility",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("private", "Private"),
                    ("users_selected", "Users Selected"),
                    ("connection_groups_selected", "Connection Groups Selected"),
                    ("connections", "Connections"),
                    ("subscribers_paid", "Subscribers Paid"),
                    ("subscribers", "Subscribers"),
                    ("internal", "Internal"),
                    ("public", "Public"),
                ],
                choices_enum=neuronhub.apps.anonymizer.fields.Visibility,
                default="private",
                max_length=26,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tools",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="recommended_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="post_recommended", to="users.userconnectiongroup"
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="recommended_to_users",
            field=models.ManyToManyField(
                blank=True, related_name="post_recommended", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="visibility",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("private", "Private"),
                    ("users_selected", "Users Selected"),
                    ("connection_groups_selected", "Connection Groups Selected"),
                    ("connections", "Connections"),
                    ("subscribers_paid", "Subscribers Paid"),
                    ("subscribers", "Subscribers"),
                    ("internal", "Internal"),
                    ("public", "Public"),
                ],
                choices_enum=neuronhub.apps.anonymizer.fields.Visibility,
                default="private",
                max_length=26,
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="visible_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="tools_visible", to="users.userconnectiongroup"
            ),
        ),
        migrations.AddField(
            model_name="tool",
            name="visible_to_users",
            field=models.ManyToManyField(
                blank=True, related_name="tools_visible", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="author",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviews",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="recommended_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_recommended", to="users.userconnectiongroup"
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="recommended_to_users",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_recommended", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="visible_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_visible", to="users.userconnectiongroup"
            ),
        ),
        migrations.AlterField(
            model_name="toolreview",
            name="visible_to_users",
            field=models.ManyToManyField(
                blank=True, related_name="reviews_visible", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
