# Generated by Django 5.2 on 2025-04-28 23:51

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_toolcompany_toolcompanyownership_and_more"),
        ("tools", "0042_remove_toolreview_orgs_remove_toolreview_tool_tags_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="tool",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="toolreviewtag",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="toolreviewvote",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="tooltag",
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name="tooltagvote",
            unique_together=None,
        ),
        migrations.DeleteModel(
            name="Company",
        ),
        migrations.DeleteModel(
            name="CompanyOwnership",
        ),
        migrations.DeleteModel(
            name="HistoricalCompany",
        ),
        migrations.DeleteModel(
            name="HistoricalTool",
        ),
        migrations.DeleteModel(
            name="HistoricalToolReview",
        ),
        migrations.DeleteModel(
            name="ToolStatsGithub",
        ),
        migrations.DeleteModel(
            name="Tool",
        ),
        migrations.DeleteModel(
            name="ToolAlternative",
        ),
        migrations.DeleteModel(
            name="ToolReview",
        ),
        migrations.DeleteModel(
            name="ToolReviewTag",
        ),
        migrations.DeleteModel(
            name="ToolReviewVote",
        ),
        migrations.DeleteModel(
            name="ToolTag",
        ),
        migrations.DeleteModel(
            name="ToolTagVote",
        ),
    ]
