# Generated by Django 5.2.11 on 2026-03-19 23:15

import django_choices_field.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SiteConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="NeuronHub", max_length=255)),
                (
                    "domain",
                    models.CharField(blank=True, default="neuronhub.app", max_length=255),
                ),
                (
                    "slug",
                    django_choices_field.fields.TextChoicesField(
                        choices=[("neuronhub", "Neuronhub"), ("pg", "Probablygood")],
                        default="neuronhub",
                        help_text="Identifier. Also matches /client/src/sites/{directory}/",
                        max_length=9,
                    ),
                ),
                ("logo", models.ImageField(blank=True, null=True, upload_to="sites/logos/")),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Show in the email footer (eg for job subscriptions)",
                        max_length=512,
                    ),
                ),
                (
                    "email_template_subscription_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Override jobs/job_alert.html. Leave blank to use the default file template.",
                    ),
                ),
                (
                    "email_template_subscription_confirmation_html",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="Override jobs/job_alert_confirmation.html. Leave blank to use the default file template.",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
