# Generated by Django 5.2.11 on 2026-03-20 00:58

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="feedback_form_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL for the feedback form link in emails",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="submit_job_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL for 'landed a role' / 'report placement' link in emails",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email_template_subscription_confirmation_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Specify to override the jobs/job_alert_confirmation.html email template. Leave blank to use the default template.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email_template_subscription_html",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Specify to override the jobs/job_alert.html email template. Leave blank to use the default template.",
            ),
        ),
    ]
