# Generated by Django 5.2.11 on 2026-03-20 23:57

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0002_siteconfig_feedback_form_url_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="siteconfig",
            name="email_template_subscription_confirmation_html",
        ),
        migrations.RemoveField(
            model_name="siteconfig",
            name="email_template_subscription_html",
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="email_template_job_alert",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Specify to override the jobs/job_subscription.html email template. Leave blank to use the default template. Test by saving the updated Site Config, and then pressing the 'SEND TEST * EMAIL TO YOURSELF' buttons in the top right corner.",
                verbose_name="Template Job alert",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="email_template_job_alert_confirmation",
            field=models.TextField(
                blank=True,
                default="",
                help_text="Specify to override the jobs/job_subscription_confirmation.html email template. Leave blank to use the default template. Test by saving the updated Site Config, and then pressing the 'SEND TEST * EMAIL TO YOURSELF' buttons in the top right corner.",
                verbose_name="Template Job alert confirmation",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Show in the email footer (eg for Job notification emails) for US CAN-SPAM compliance. Example: `447 Sutter St Ste 405 #675 · San Francisco, CA 94108`",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="submit_job_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL for 'landed a role' / 'report placement' link in Job notification emails",
                max_length=512,
            ),
        ),
    ]
