# Generated by Django 5.2.11 on 2026-03-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0003_remove_siteconfig_email_template_subscription_confirmation_html_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siteconfig',
            name='logo',
        ),
    ]
