# Generated by Django 5.2.11 on 2026-03-21 04:08
from django.db import migrations
from django.db import models

import neuronhub.apps.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0004_remove_siteconfig_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="address",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Show in the email footer (eg for Job alert emails) for US CAN-SPAM compliance. Example: `442 Sutter St Ste 401 #625 · San Francisco, CA 94102`",
                max_length=512,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email_template_job_alert",
            field=neuronhub.apps.db.fields.HtmlField(
                blank=True,
                default="",
                help_text="Specify to override the jobs/job_alert.html email template. Leave blank to use the default template. Test by saving the updated Site Config, and then pressing the 'SEND TEST * EMAIL TO YOURSELF' buttons in the top right corner.",
                verbose_name="Template Job alert",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email_template_job_alert_confirmation",
            field=neuronhub.apps.db.fields.HtmlField(
                blank=True,
                default="",
                help_text="Specify to override the jobs/job_alert_confirmation.html email template. Leave blank to use the default template. Test by saving the updated Site Config, and then pressing the 'SEND TEST * EMAIL TO YOURSELF' buttons in the top right corner.",
                verbose_name="Template Job alert confirmation",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="submit_job_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="URL for 'landed a role' / 'report placement' link in Job alert emails",
                max_length=512,
            ),
        ),
    ]
