# Generated by Django 5.2.11 on 2026-03-22 09:31

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations
from django.db import models


def populate_links(apps, schema_editor):
    SiteConfig = apps.get_model("sites", "SiteConfig")
    NavbarLink = apps.get_model("sites", "NavbarLink")
    FooterSection = apps.get_model("sites", "FooterSection")
    FooterLink = apps.get_model("sites", "FooterLink")

    site = SiteConfig.objects.first()
    if not site:
        return

    for i, link in enumerate(NAV_LINKS):
        NavbarLink.objects.create(site=site, order=i, **link)

    for i, (title, links) in enumerate(FOOTER_COLUMNS.items()):
        section = FooterSection.objects.create(site=site, kind="column", title=title, order=i)
        for j, link in enumerate(links):
            FooterLink.objects.create(section=section, order=j, **link)

    social_section = FooterSection.objects.create(
        site=site, kind="social", title="", order=len(FOOTER_COLUMNS)
    )
    for i, link in enumerate(SOCIAL_LINKS):
        FooterLink.objects.create(section=social_section, order=i, **link)

    bottom_section = FooterSection.objects.create(
        site=site, kind="bottom", title="", order=len(FOOTER_COLUMNS) + 1
    )
    for i, link in enumerate(BOTTOM_LINKS):
        FooterLink.objects.create(section=bottom_section, order=i, **link)


NAV_LINKS = [
    {"label": "Career Guide", "href": "https://probablygood.org/career-guide/"},
    {"label": "Career Profiles", "href": "https://probablygood.org/career-profiles/"},
    {"label": "Job Board", "href": "https://jobs.probablygood.org/"},
    {"label": "Explore", "href": "https://probablygood.org/explore/"},
    {"label": "Advising", "href": "https://probablygood.org/advising/"},
    {"label": "About", "href": "https://probablygood.org/about/"},
]

FOOTER_COLUMNS = {
    "Content": [
        {"label": "Career Guide", "href": "https://probablygood.org/career-guide/"},
        {"label": "Career Profiles", "href": "https://probablygood.org/career-profiles/"},
        {"label": "Cause Areas", "href": "https://probablygood.org/cause-areas/"},
        {"label": "Degree Paths", "href": "https://probablygood.org/degree-paths/"},
        {"label": "Core Concepts", "href": "https://probablygood.org/core-concepts/"},
        {"label": "Interviews", "href": "https://probablygood.org/interviews/"},
        {"label": "Explore", "href": "https://probablygood.org/explore/"},
    ],
    "Services": [
        {"label": "1:1 Advising", "href": "https://probablygood.org/advising/"},
        {"label": "Job Board", "href": "https://jobs.probablygood.org/"},
        {"label": "Workshops", "href": "https://probablygood.org/workshops/"},
    ],
    "About": [
        {"label": "Learn more", "href": "https://probablygood.org/about/"},
        {"label": "Get in touch", "href": "https://probablygood.org/contact/"},
        {"label": "Donate", "href": "https://probablygood.org/donate/"},
    ],
}

SOCIAL_LINKS = [
    {"label": "Email", "href": "https://probablygood.org/newsletter/", "icon": "email"},
    {
        "label": "LinkedIn",
        "href": "https://www.linkedin.com/company/probably-good/",
        "icon": "linkedin",
    },
]

BOTTOM_LINKS = [
    {"label": "Privacy Policy", "href": "https://probablygood.org/privacy-policy/"},
    {"label": "Terms of Service", "href": "https://probablygood.org/terms-of-service/"},
    {"label": "Cookie Preferences", "href": "https://probablygood.org/about/#manage_cookies"},
]


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0005_alter_siteconfig_address_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="FooterSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "kind",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("column", "Column"),
                            ("social", "Social"),
                            ("bottom", "Bottom"),
                        ],
                        default="column",
                        max_length=6,
                    ),
                ),
                ("title", models.CharField(blank=True, default="", max_length=255)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="footer_sections",
                        to="sites.siteconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("href", models.URLField(max_length=512)),
                (
                    "icon",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("email", "Email"),
                            ("linkedin", "Linkedin"),
                            ("matrix", "Matrix"),
                            ("discord", "Discord"),
                            ("mastodon", "Mastodon"),
                            ("github", "Github"),
                            ("youtube", "Youtube"),
                            ("substack", "Substack"),
                            ("twitter", "Twitter"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                        ],
                        default=None,
                        max_length=9,
                        null=True,
                    ),
                ),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="sites.footersection",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="NavbarLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("label", models.CharField(max_length=255)),
                ("href", models.URLField(max_length=512)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
                (
                    "site",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_links",
                        to="sites.siteconfig",
                    ),
                ),
            ],
            options={
                "ordering": ["order"],
            },
        ),
        migrations.RunPython(populate_links, migrations.RunPython.noop),
    ]
