# Generated by Django 5.2.11 on 2026-03-24 08:05
import textwrap

from django.conf import settings
from django.db import migrations
from django.db import models

from neuronhub.apps.db.fields import HtmlField


def populate_pg_data(apps, schema_editor):
    SiteConfig = apps.get_model("sites", "SiteConfig")
    site = SiteConfig.objects.first()

    if settings.VITE_SITE == "pg":
        site.logo_url = "https://probablygood.org/wp-content/uploads/probably-good-logo-540.png"
        site.email_html_about_us = textwrap.dedent("""
            At <a href="https://probablygood.org" style="color:#338050;text-decoration:underline;">Probably Good</a>,
            we&#39;re dedicated to helping people build careers that are good for them and for the world.
            Read our <a href="https://probablygood.org/career-guide" style="color:#338050;text-decoration:underline;">career guide</a>,
            apply for <a href="https://probablygood.org/advising" style="color:#338050;text-decoration:underline;">1:1 advising</a>,
            or <a href="https://probablygood.org/explore" style="color:#338050;text-decoration:underline;">explore our other content</a>.
        """)
        site.email_html_feedback_request = textwrap.dedent("""
            We&#39;re a nonprofit driven by impact, so a quick update from you
            makes a huge difference to our ability to keep providing this service for free.
        """)
        site.save()


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0007_populate_siteconfig_email_templates"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="email_html_about_us",
            field=models.TextField(
                blank=True,
                default="",
                help_text="HTML for the 'About' paragraph in job alert emails. Supports inline-styled <a> tags. Leave blank for generic text.",
                verbose_name="About section HTML",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="email_html_feedback_request",
            field=HtmlField(
                blank=True,
                default="",
                help_text="HTML for the 'landed a role' section. Supports inline-styled <a> tags. Leave blank for generic text.",
                verbose_name="M&E body HTML",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="logo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Absolute URL to the site logo PNG (exported at 2-3x for retina). Displayed at width=180 in email headers. Leave blank for text-only header.",
                max_length=512,
            ),
        ),
        migrations.RunPython(populate_pg_data, migrations.RunPython.noop),
    ]
