# Generated by Django 5.2.11 on 2026-03-26 02:41

from django.db import migrations
from django.db import models

import neuronhub.apps.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0008_siteconfig_email_about_html_siteconfig_email_me_body_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="jobs_url_utm_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="UTM source param appended to external job/org URLs on the frontend, eg `{url}?utm_source=probablygood_board`",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email_html_about_us",
            field=models.TextField(
                blank=True,
                default="",
                help_text="HTML for the 'About' paragraph in job alert emails. Supports inline-styled <a> tags. Leave blank for generic text.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email_html_feedback_request",
            field=neuronhub.apps.db.fields.HtmlField(
                blank=True,
                default="",
                help_text="HTML for the 'landed a role' section. Supports inline-styled <a> tags. Leave blank for generic text.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="logo_url",
            field=models.URLField(
                blank=True,
                default="",
                help_text="Absolute URL to the site logo PNG (exported at 2-3x for retina). Displayed at width=180px in email headers. Leave blank for text-only header.",
                max_length=512,
            ),
        ),
    ]
