# Generated by Django 5.2.11 on 2026-03-27 19:26

import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0010_merge_20260326_2108"),
    ]

    operations = [
        migrations.AddField(
            model_name="navbarlink",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="children",
                to="sites.navbarlink",
            ),
        ),
    ]
