# Generated by Django 5.2.11 on 2026-03-31 02:05

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0011_navbarlinksection_navbarlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="siteconfig",
            name="contact_email",
            field=models.EmailField(
                default="support@neuronhub.app",
                help_text="Used eg in the 'Contact' modal form",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="sender_email",
            field=models.EmailField(
                default="support@neuronhub.app",
                help_text="Eg used as the sender of the Job Alerts emails. But backend will use DEFAULT_FROM_EMAIL env instead for sending eg user auth management emails (password resets, etc).",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="jobs_url_utm_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="UTM source param appended to external job/org URLs on the frontend, eg `{url}?utm_source=probablygood`",
                max_length=255,
            ),
        ),
    ]
