# Generated by Django 5.2.11 on 2026-04-03 04:06

import django.db.models.deletion
import django_choices_field.fields
import simple_history.models
from django.conf import settings
from django.db import migrations
from django.db import models

import neuronhub.apps.db.fields


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0012_siteconfig_contact_email_siteconfig_sender_email_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="contact_email",
            field=models.EmailField(
                default="support@nha2.test",
                help_text="Used for `reply-to` email and the 'Contact' modal form",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="sender_email",
            field=models.EmailField(
                default="support@nha2.test",
                help_text="Eg used as the sender of the Job Alerts emails. But backend will use DEFAULT_FROM_EMAIL env instead for sending eg user auth management emails (password resets, etc).",
                max_length=254,
            ),
        ),
        migrations.CreateModel(
            name="HistoricalSiteConfig",
            fields=[
                (
                    "id",
                    models.BigIntegerField(
                        auto_created=True, blank=True, db_index=True, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(default="NeuronHub", max_length=255)),
                (
                    "domain",
                    models.CharField(blank=True, default="neuronhub.app", max_length=255),
                ),
                (
                    "slug",
                    django_choices_field.fields.TextChoicesField(
                        choices=[("neuronhub", "Neuronhub"), ("pg", "Probablygood")],
                        default="neuronhub",
                        help_text="Identifier. Also matches /client/src/sites/{directory}/",
                        max_length=9,
                    ),
                ),
                (
                    "sender_email",
                    models.EmailField(
                        default="support@nha2.test",
                        help_text="Eg used as the sender of the Job Alerts emails. But backend will use DEFAULT_FROM_EMAIL env instead for sending eg user auth management emails (password resets, etc).",
                        max_length=254,
                    ),
                ),
                (
                    "contact_email",
                    models.EmailField(
                        default="support@nha2.test",
                        help_text="Used for `reply-to` email and the 'Contact' modal form",
                        max_length=254,
                    ),
                ),
                (
                    "logo_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="Absolute URL to the site logo PNG (exported at 2-3x for retina). Displayed at width=180px in email headers. Leave blank for text-only header.",
                        max_length=512,
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Show in the email footer (eg for Job alert emails) for US CAN-SPAM compliance. Example: `442 Sutter St Ste 401 #625 · San Francisco, CA 94102`",
                        max_length=512,
                    ),
                ),
                (
                    "feedback_form_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL for the feedback form link in emails",
                        max_length=512,
                    ),
                ),
                (
                    "submit_job_url",
                    models.URLField(
                        blank=True,
                        default="",
                        help_text="URL for 'landed a role' / 'report placement' link in Job alert emails",
                        max_length=512,
                    ),
                ),
                (
                    "jobs_url_utm_source",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="UTM source param appended to external job/org URLs on the frontend, eg `{url}?utm_source=probablygood`",
                        max_length=255,
                    ),
                ),
                (
                    "email_html_about_us",
                    neuronhub.apps.db.fields.HtmlField(
                        blank=True,
                        default="",
                        help_text="HTML for the 'About' paragraph in job alert emails. Supports inline-styled <a> tags. Leave blank for generic text.",
                    ),
                ),
                (
                    "email_html_feedback_request",
                    neuronhub.apps.db.fields.HtmlField(
                        blank=True,
                        default="",
                        help_text="HTML for the 'landed a role' section. Supports inline-styled <a> tags. Leave blank for generic text.",
                    ),
                ),
                (
                    "email_template_job_alert",
                    neuronhub.apps.db.fields.HtmlField(
                        blank=True,
                        default="",
                        help_text="Specify to override the jobs/job_alert.html email template. Leave blank to use the default template. Test by saving the updated Site Config, and then pressing the 'SEND TEST * EMAIL TO YOURSELF' buttons in the top right corner.",
                        verbose_name="Template Job alert",
                    ),
                ),
                (
                    "email_template_job_alert_confirmation",
                    neuronhub.apps.db.fields.HtmlField(
                        blank=True,
                        default="",
                        help_text="Specify to override the jobs/job_alert_confirmation.html email template. Leave blank to use the default template. Test by saving the updated Site Config, and then pressing the 'SEND TEST * EMAIL TO YOURSELF' buttons in the top right corner.",
                        verbose_name="Template Job alert confirmation",
                    ),
                ),
                ("history_id", models.AutoField(primary_key=True, serialize=False)),
                ("history_date", models.DateTimeField(db_index=True)),
                ("history_change_reason", models.CharField(max_length=100, null=True)),
                (
                    "history_type",
                    models.CharField(
                        choices=[("+", "Created"), ("~", "Changed"), ("-", "Deleted")],
                        max_length=1,
                    ),
                ),
                (
                    "history_user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "historical site config",
                "verbose_name_plural": "historical site configs",
                "ordering": ("-history_date", "-history_id"),
                "get_latest_by": ("history_date", "history_id"),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
