# Generated by Django 5.2.11 on 2026-04-02 09:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0012_siteconfig_contact_email_siteconfig_sender_email_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="siteconfig",
            name="contact_email",
            field=models.EmailField(
                default="support@localhost",
                help_text="Used eg in the 'Contact' modal form",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="sender_email",
            field=models.EmailField(
                default="support@localhost",
                help_text="Eg used as the sender of the Job Alerts emails. But backend will use DEFAULT_FROM_EMAIL env instead for sending eg user auth management emails (password resets, etc).",
                max_length=254,
            ),
        ),
    ]
