# Generated by Django 5.2.11 on 2026-04-03 05:56
from django.conf import settings
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0013_alter_siteconfig_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsiteconfig",
            name="sender_email_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="With it the system will send emails as `From: {sender_email_name} <{sender_email}>`, otherwise will send as `From: <{sender_email}>`",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="sender_email_name",
            field=models.CharField(
                blank=True,
                default="",
                help_text="With it the system will send emails as `From: {sender_email_name} <{sender_email}>`, otherwise will send as `From: <{sender_email}>`",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsiteconfig",
            name="contact_email",
            field=models.EmailField(
                default=settings.DEFAULT_FROM_EMAIL,
                help_text="Used for `reply-to` email and the 'Contact' modal form",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="historicalsiteconfig",
            name="sender_email",
            field=models.EmailField(
                default=settings.DEFAULT_FROM_EMAIL,
                help_text="Eg used as the sender of the Job Alerts emails. But backend will use DEFAULT_FROM_EMAIL env instead for sending eg user auth management emails (password resets, etc).",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="contact_email",
            field=models.EmailField(
                default=settings.DEFAULT_FROM_EMAIL,
                help_text="Used for `reply-to` email and the 'Contact' modal form",
                max_length=254,
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="sender_email",
            field=models.EmailField(
                default=settings.DEFAULT_FROM_EMAIL,
                help_text="Eg used as the sender of the Job Alerts emails. But backend will use DEFAULT_FROM_EMAIL env instead for sending eg user auth management emails (password resets, etc).",
                max_length=254,
            ),
        ),
    ]
