# Generated by Django 5.2.11 on 2026-04-07 11:40

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0015_alter_historicalsiteconfig_contact_email_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsiteconfig",
            name="is_enable_job_alerts",
            field=models.BooleanField(
                default=True, help_text="Manages the hourly JobAlerts sending."
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="is_enable_job_alerts",
            field=models.BooleanField(
                default=True, help_text="Manages the hourly JobAlerts sending."
            ),
        ),
    ]
