# Generated by Django 5.2.11 on 2026-04-10 02:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0016_historicalsiteconfig_is_enable_job_alerts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsiteconfig",
            name="is_job_alerts_staff_only",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, job alerts are only sent to emails that belong to a User with is_staff=True. Use to test emails in prod safely.",
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="is_job_alerts_staff_only",
            field=models.BooleanField(
                default=False,
                help_text="When enabled, job alerts are only sent to emails that belong to a User with is_staff=True. Use to test emails in prod safely.",
            ),
        ),
    ]
