# Generated by Django 6.0.5 on 2026-06-30 09:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0018_migrate_job_alert_template_to_url_tag"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeoMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "path",
                    models.CharField(
                        help_text='URL path, e.g. "/jobs". Use "/" for home.',
                        max_length=255,
                        unique=True,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=512)),
                ("meta_description", models.CharField(blank=True, max_length=512)),
                ("meta_image_url", models.URLField(blank=True, max_length=512)),
            ],
            options={
                "ordering": ["path"],
            },
        ),
    ]
