# Generated by Django 6.0.5 on 2026-08-05 09:38

import neuronhub.apps.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0018_migrate_job_alert_template_to_url_tag"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalsiteconfig",
            name="email_html_about_us",
            field=neuronhub.apps.db.fields.HtmlField(
                blank=True,
                default="",
                help_text="HTML for the 'About' paragraph in job alert emails. Supports inline-styled anchor tags. Leave blank for generic text.",
            ),
        ),
        migrations.AlterField(
            model_name="historicalsiteconfig",
            name="email_html_feedback_request",
            field=neuronhub.apps.db.fields.HtmlField(
                blank=True,
                default="",
                help_text="HTML for the 'landed a role' section. Supports inline-styled anchor tags. Leave blank for generic text.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email_html_about_us",
            field=neuronhub.apps.db.fields.HtmlField(
                blank=True,
                default="",
                help_text="HTML for the 'About' paragraph in job alert emails. Supports inline-styled anchor tags. Leave blank for generic text.",
            ),
        ),
        migrations.AlterField(
            model_name="siteconfig",
            name="email_html_feedback_request",
            field=neuronhub.apps.db.fields.HtmlField(
                blank=True,
                default="",
                help_text="HTML for the 'landed a role' section. Supports inline-styled anchor tags. Leave blank for generic text.",
            ),
        ),
    ]
