# Generated by Django 6.0.5 on 2026-07-24 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sites", "0018_migrate_job_alert_template_to_url_tag"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalsiteconfig",
            name="landing_meta_title_template",
            field=models.CharField(
                blank=True,
                default="{label}",
                help_text="Meta title template. `{label}` is the landing page's own `label` field. Shared fallback used when the page's own meta_title is blank. Append the site's brand here, eg `{label} | Probably Good`.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="historicalsiteconfig",
            name="landing_subtitle_default",
            field=models.CharField(
                blank=True,
                default="Curated high-impact jobs for people who want to make a difference.",
                help_text="Shared subtitle fallback. Used when the page's own subtitle is blank.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="historicalsiteconfig",
            name="landing_title_template",
            field=models.CharField(
                blank=True,
                default="Find {label} that are good for you and for the world.",
                help_text="H1 template. `{label}` is the landing page's own `label` field, eg `Impactful Climate Change Jobs`. Used when the page's own title is blank.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="landing_meta_title_template",
            field=models.CharField(
                blank=True,
                default="{label}",
                help_text="Meta title template. `{label}` is the landing page's own `label` field. Shared fallback used when the page's own meta_title is blank. Append the site's brand here, eg `{label} | Probably Good`.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="landing_subtitle_default",
            field=models.CharField(
                blank=True,
                default="Curated high-impact jobs for people who want to make a difference.",
                help_text="Shared subtitle fallback. Used when the page's own subtitle is blank.",
                max_length=512,
            ),
        ),
        migrations.AddField(
            model_name="siteconfig",
            name="landing_title_template",
            field=models.CharField(
                blank=True,
                default="Find {label} that are good for you and for the world.",
                help_text="H1 template. `{label}` is the landing page's own `label` field, eg `Impactful Climate Change Jobs`. Used when the page's own title is blank.",
                max_length=512,
            ),
        ),
    ]
