# Generated by Django 5.2b1 on 2025-04-11 00:05

import django.db.models.deletion
import django_choices_field.fields
import neuronhub.apps.anonymizer.fields
import neuronhub.apps.db.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("users", "0004_user_username_alter_user_email_alter_user_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("object_id", models.PositiveIntegerField()),
                (
                    "visibility",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("private", "Private"),
                            ("connection_groups_selected", "Connection Groups"),
                            ("connections", "Connections"),
                            ("internal", "Internal"),
                            ("public", "Public"),
                        ],
                        choices_enum=neuronhub.apps.anonymizer.fields.Visibility,
                        default="private",
                        max_length=17,
                    ),
                ),
                ("content", neuronhub.apps.db.fields.MarkdownField(blank=True)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="comments.comment",
                    ),
                ),
                (
                    "seen_by_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Marked 'seen' if present in browser's ViewBox for 4 seconds",
                        related_name="comments_seen",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "visible_to_groups",
                    models.ManyToManyField(
                        blank=True,
                        related_name="comments_visible",
                        to="users.userconnectiongroup",
                    ),
                ),
                (
                    "visible_to_users",
                    models.ManyToManyField(
                        blank=True, related_name="comments_visible", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CommentVoteModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_vote_positive", models.BooleanField(blank=True, null=True)),
                ("is_vote_changed_my_mind", models.BooleanField(default=False)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="comment_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="votes",
                        to="comments.comment",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="comment",
            index=models.Index(
                fields=["content_type", "object_id"], name="comments_co_content_cff8bd_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="commentvotemodel",
            unique_together={("comment", "author")},
        ),
    ]
