# Generated by Django 5.2b1 on 2025-04-11 00:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("comments", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="CommentVoteModel",
            new_name="CommentVote",
        ),
    ]
