# Generated by Django 5.2 on 2025-06-15 23:57

import django_extensions.db.fields
import timezone_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Org",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    django_extensions.db.fields.AutoSlugField(
                        blank=True, editable=False, populate_from="name", unique=True
                    ),
                ),
                ("domain", models.CharField(max_length=255, unique=True)),
                ("tz", timezone_field.fields.TimeZoneField(default="America/Los_Angeles")),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
