# Generated by Django 5.2.8 on 2025-11-28 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
