# Generated by Django 5.1 on 2024-09-03 18:02

import django_extensions.db.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="domain",
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name="org",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                blank=True, editable=False, populate_from="name", unique=True
            ),
        ),
    ]
