# Generated by Django 5.2.11 on 2026-02-26 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0002_alter_org_created_at"),
        ("posts", "0030_posttagcategory_posttag_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="is_highlighted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="org",
            name="jobs_page_url",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AddField(
            model_name="org",
            name="tags_area",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"categories__name": "area"},
                related_name="tags_org_area",
                to="posts.posttag",
            ),
        ),
        migrations.AddField(
            model_name="org",
            name="website",
            field=models.CharField(blank=True, max_length=1024),
        ),
        migrations.AlterField(
            model_name="org",
            name="domain",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
