# Generated by Django 5.2.11 on 2026-02-26 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0003_org_is_highlighted_org_jobs_page_url_org_tags_area_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="logo",
            field=models.ImageField(blank=True, null=True, upload_to="orgs/logos/"),
        ),
    ]
