# Generated by Django 5.2.11 on 2026-03-11 01:28

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0004_org_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
