# Generated by Django 5.2.11 on 2026-03-27 05:12

from django.db import migrations
from django.db import models

from neuronhub.apps.sites.models import url_with_utm_help_text


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0005_org_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="website_with_utm",
            field=models.CharField(
                blank=True, max_length=1024, help_text=url_with_utm_help_text
            ),
        ),
    ]
