# Generated by Django 6.0.5 on 2026-07-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0007_merge_duplicate_orgs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="org",
            name="name",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
