# Generated by Django 6.0.5 on 2026-07-23 12:36

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orgs", "0008_alter_org_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="org",
            name="org_type",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Nonprofit", "Nonprofit"),
                    ("For-Profit", "For Profit"),
                    ("Government", "Government"),
                    ("University", "University"),
                    ("International Institution", "International Institution"),
                    ("Think Tank", "Think Tank"),
                ],
                default=None,
                max_length=25,
                null=True,
            ),
        ),
    ]
