# Generated by Django 5.2.7 on 2025-10-23 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("highlighter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posthighlight",
            name="text_postfix",
            field=models.CharField(blank=True, help_text="for position matcher", max_length=64),
        ),
        migrations.AddField(
            model_name="posthighlight",
            name="text_prefix",
            field=models.CharField(blank=True, help_text="for position matcher", max_length=64),
        ),
    ]
