# Generated by Django 5.2.7 on 2025-10-30 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("highlighter", "0002_posthighlight_text_postfix_posthighlight_text_prefix"),
        ("posts", "0020_alter_historicalpost_slug_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posthighlight",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="post_highlights",
                related_query_name="post_highlight",
                to="posts.post",
            ),
        ),
    ]
