# Generated by Django 5.2 on 2025-04-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="source",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AddField(
            model_name="post",
            name="source",
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
