# Generated by Django 5.2 on 2025-06-16 03:28

import neuronhub.apps.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttagvote",
            name="comment",
            field=neuronhub.apps.db.fields.MarkdownField(
                blank=True, help_text="Eg clarifying author's opinion re the tag"
            ),
        ),
    ]
