# Generated by Django 5.2 on 2025-04-23 03:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0002_historicalpost_source_post_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="users_library",
            field=models.ManyToManyField(
                blank=True, related_name="library_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="users_read_later",
            field=models.ManyToManyField(
                blank=True, related_name="read_later_posts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
