# Generated by Django 5.2 on 2025-04-23 04:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_alter_post_users_library_alter_post_users_read_later"),
        ("users", "0006_user_id_uuid_alter_user_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="recommended_to_groups",
            field=models.ManyToManyField(
                blank=True, related_name="posts_recommended", to="users.userconnectiongroup"
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="recommended_to_users",
            field=models.ManyToManyField(
                blank=True, related_name="posts_recommended", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
