# Generated by Django 5.2 on 2025-06-18 05:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_posttagvote_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="is_review_later",
            field=models.BooleanField(
                default=False,
                help_text="Would be better as a M2M with a through model on Post.users_read_later, but that's a bit too complex atm. It indicates a review with `content` that's more like a note re why User might want to review it or not.",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="is_review_later",
            field=models.BooleanField(
                default=False,
                help_text="Would be better as a M2M with a through model on Post.users_read_later, but that's a bit too complex atm. It indicates a review with `content` that's more like a note re why User might want to review it or not.",
            ),
        ),
    ]
