# Generated by Django 5.2 on 2025-06-19 00:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0004_historicalpost_is_review_later_post_is_review_later"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpost",
            name="review_content_cons",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="review_content_pros",
        ),
        migrations.RemoveField(
            model_name="post",
            name="review_content_cons",
        ),
        migrations.RemoveField(
            model_name="post",
            name="review_content_pros",
        ),
    ]
