# Generated by Django 5.2.3 on 2025-06-20 23:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_remove_historicalpost_review_content_cons_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PostReviewTag",
        ),
    ]
