# Generated by Django 5.2 on 2025-04-29 02:58

import django_choices_field.fields
import neuronhub.apps.posts.models.posts
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_toolcompany_toolcompanyownership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posttagvote",
            name="comment",
        ),
        migrations.AddField(
            model_name="historicalpost",
            name="tool_type",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("software", "Software"),
                    ("material", "Material"),
                    ("saas", "Saas"),
                    ("other", "Other"),
                ],
                choices_enum=neuronhub.apps.posts.models.posts.Post.ToolType,
                default=None,
                max_length=8,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="tool_type",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("software", "Software"),
                    ("material", "Material"),
                    ("saas", "Saas"),
                    ("other", "Other"),
                ],
                choices_enum=neuronhub.apps.posts.models.posts.Post.ToolType,
                default=None,
                max_length=8,
                null=True,
            ),
        ),
    ]
