# Generated by Django 5.2.4 on 2025-07-31 22:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_delete_postreviewtag"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicaltoolcompany",
            name="slug",
        ),
    ]
