# Generated by Django 5.2 on 2025-05-03 23:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0006_remove_posttagvote_comment_historicalpost_tool_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="comments",
        ),
        migrations.AddField(
            model_name="post",
            name="children",
            field=models.ManyToManyField(
                blank=True, help_text="ATM only PostComments", to="posts.post"
            ),
        ),
        migrations.AddField(
            model_name="postvote",
            name="is_changed_my_mind",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="users_library",
            field=models.ManyToManyField(
                blank=True, related_name="library", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="users_read_later",
            field=models.ManyToManyField(
                blank=True, related_name="read_later", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
