# Generated by Django 5.2 on 2025-06-03 02:10

import neuronhub.apps.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_remove_post_comments_post_children_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="review_content_cons",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpost",
            name="review_content_pros",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="review_content_cons",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="review_content_pros",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
    ]
