# Generated by Django 5.2.4 on 2025-08-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0007_remove_historicaltoolcompany_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpost",
            name="review_importance",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="review_importance",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
