# Generated by Django 5.2 on 2025-06-12 05:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_historicalpost_review_content_cons_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="children",
        ),
        migrations.AlterField(
            model_name="post",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Can link to a PostTool (type=review), PostReview (type=comment), PostComment (type=comment)",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="children",
                to="posts.post",
            ),
        ),
    ]
