# Generated by Django 5.2.4 on 2025-08-03 06:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0008_alter_historicalpost_review_importance_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpost",
            name="review_rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Split on 5 categories: very dissatisfied, dissatisfied, neutral, satisfied, very satisfied",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="review_rating",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="Split on 5 categories: very dissatisfied, dissatisfied, neutral, satisfied, very satisfied",
                null=True,
            ),
        ),
    ]
