# Generated by Django 5.2.4 on 2025-08-14 22:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_alter_historicalpost_review_rating_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttag",
            name="tag_parent",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="tag_children",
                to="posts.posttag",
            ),
        ),
    ]
