# Generated by Django 5.2 on 2025-06-15 03:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0009_remove_post_children_alter_post_parent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="posttagvote",
            name="is_important",
        ),
        migrations.AddField(
            model_name="posttag",
            name="is_important",
            field=models.BooleanField(
                blank=True,
                default=False,
                help_text="\nA highly informative PostTag - shown before other tags with a visual icon \n(eg macOS, Windows, TypeScript).\nAnd helps users to easily identify tools that work on their OS or tool. \nA Post author could set it to place the Tag at the start of other tags.\n",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="posttag",
            name="is_review_tag",
            field=models.BooleanField(
                default=False,
                help_text="\nA special tag, shows the accumulative public opinion of the given topic, \nwith either positive '+' or negative '-' symbol and color. For a Software Tool it could be: \nPrivacy; Controversial; Mature; Expectation; FOSS, etc. \nThey're mostly defined the Django admins.\n",
            ),
        ),
        migrations.AlterField(
            model_name="posttagvote",
            name="tag",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="posts.posttag",
            ),
        ),
    ]
