# Generated by Django 5.2.5 on 2025-08-27 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0010_alter_posttag_tag_parent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterField(
            model_name="historicalpost",
            name="title",
            field=models.CharField(blank=True, max_length=140),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=140),
        ),
    ]
