# Generated by Django 5.2.5 on 2025-08-29 23:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0011_alter_post_options_alter_historicalpost_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="review_tags",
            field=models.ManyToManyField(
                blank=True, related_name="post_reviews", to="posts.posttag"
            ),
        ),
    ]
