# Generated by Django 5.2.6 on 2025-09-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0012_post_review_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="image",
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/images/"),
        ),
    ]
