# Generated by Django 5.2.6 on 2025-09-30 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0013_historicalpost_image_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="source_author",
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name="post",
            name="source_author",
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
