# Generated by Django 5.2.7 on 2025-10-05 00:32

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0014_historicalpost_source_author_post_source_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="category",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("knowledge", "Knowledge"),
                    ("opinion", "Opinion"),
                    ("question", "Question"),
                    ("news", "News"),
                ],
                default=None,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="category",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("knowledge", "Knowledge"),
                    ("opinion", "Opinion"),
                    ("question", "Question"),
                    ("news", "News"),
                ],
                default=None,
                max_length=9,
                null=True,
            ),
        ),
    ]
