# Generated by Django 5.1.2

from django.db import migrations, models
from neuronhub.apps.db.fields import MarkdownField


def migrate_content_to_content_polite(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.all():
        if hasattr(post, "content") and post.content:
            post.content_polite = post.content
            post.save()


def reverse_migration(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.all():
        if hasattr(post, "content_polite") and post.content_polite:
            post.content = post.content_polite
            post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0015_historicalpost_category_post_category"),
    ]

    operations = [
        # Add new fields
        migrations.AddField(
            model_name="post",
            name="content_polite",
            field=MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content_direct",
            field=MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="post",
            name="content_rant",
            field=MarkdownField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpost",
            name="content_polite",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpost",
            name="content_direct",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="historicalpost",
            name="content_rant",
            field=models.TextField(blank=True),
        ),
        # Run data migration
        migrations.RunPython(migrate_content_to_content_polite, reverse_migration),
        # Remove old field
        migrations.RemoveField(
            model_name="post",
            name="content",
        ),
        migrations.RemoveField(
            model_name="historicalpost",
            name="content",
        ),
    ]
