# Generated by Django 5.2.7 on 2025-10-08 23:13

import neuronhub.apps.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0016_content_field_split"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpost",
            name="content_direct",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalpost",
            name="content_polite",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
        migrations.AlterField(
            model_name="historicalpost",
            name="content_rant",
            field=neuronhub.apps.db.fields.MarkdownField(blank=True),
        ),
    ]
