# Generated by Django 5.2.7 on 2025-10-19 19:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0017_alter_historicalpost_content_direct_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpost",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="historicalpost",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="source",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
