# Generated by Django 5.2.7 on 2025-10-20 03:40

import django_extensions.db.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0019_alter_slug_to_optional"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalpost",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                allow_duplicates=True, blank=True, editable=False, populate_from="title"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=django_extensions.db.fields.AutoSlugField(
                allow_duplicates=True, blank=True, editable=False, populate_from="title"
            ),
        ),
    ]
