# Generated by Django 5.2.7 on 2025-10-31 04:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0020_alter_historicalpost_slug_alter_post_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalpost",
            name="parent_root",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                help_text="eg Post<Comment> can have a .parent Post<Comment>, but .parent_root is always not a Comment",
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="posts.post",
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="collapsed_by_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Collapsed in the UI, eg CommentThread",
                related_name="posts_collapsed",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="post",
            name="parent_root",
            field=models.ForeignKey(
                blank=True,
                help_text="eg Post<Comment> can have a .parent Post<Comment>, but .parent_root is always not a Comment",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="root_children",
                to="posts.post",
            ),
        ),
    ]
