# Generated by Django 5.2.8 on 2025-11-22 07:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0021_historicalpost_parent_root_post_collapsed_by_users_and_more"),
    ]

    operations = []
