# Generated by Django 5.2.8 on 2025-11-26 00:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0022_historicalpost_comment_thread_root_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="historicalpost",
            name="parent_root",
        ),
    ]
