# Generated by Django 5.2.8 on 2025-11-28 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0023_remove_historicalpost_comment_thread_root_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicaltoolcompany",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="posttoolstatsgithub",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="toolcompany",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="toolcompanyownership",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
