# Generated by Django 5.2.9 on 2026-01-09 01:23

import django_choices_field.fields
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0026_alter_historicalpost_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "votes_multiplier",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Since FE sort uses HackerNews votes (avg 100-800 per Post) - we multiply NHA Post votes by it to make them discoverable.",
                    ),
                ),
            ],
            options={
                "verbose_name": "Posts Config",
            },
        ),
        migrations.AlterField(
            model_name="historicalpost",
            name="visibility",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("private", "Private"),
                    ("users_selected", "Users Selected"),
                    ("connections", "Connections"),
                    ("subscribers_paid", "Subscribers Paid"),
                    ("subscribers", "Subscribers"),
                    ("internal", "Internal"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="visibility",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("private", "Private"),
                    ("users_selected", "Users Selected"),
                    ("connections", "Connections"),
                    ("subscribers_paid", "Subscribers Paid"),
                    ("subscribers", "Subscribers"),
                    ("internal", "Internal"),
                    ("public", "Public"),
                ],
                default="private",
                max_length=16,
            ),
        ),
    ]
