# Generated by Django 5.2.9 on 2026-01-22 02:59

from django.db import migrations
from django.db import models
from markdown import markdown

from neuronhub.apps.importer.models import ImportDomain
from neuronhub.apps.posts.models import PostTypeEnum


def add_ssr_to_imported_posts(apps, schema_editor):
    Post = apps.get_model("posts", "Post")
    for post in Post.objects.filter(
        post_source__domain=ImportDomain.HackerNews,
        type=PostTypeEnum.Comment,
    ):
        post.content_polite_html_ssr = markdown(post.content_polite)
        post.save()


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0027_postconfig_alter_historicalpost_visibility_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="content_polite_html_ssr",
            field=models.TextField(blank=True, help_text="Used by FE to SSR 1000+ comments"),
        ),
        migrations.RunPython(add_ssr_to_imported_posts),
    ]
