# Generated by Django 5.2.11 on 2026-02-20 05:24

import django.utils.timezone
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0029_drop_content_polite_from_imported_posts"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostTagCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("area", "Area"),
                            ("skill", "Skill"),
                            ("education", "Education"),
                            ("experience", "Experience"),
                            ("workload", "Workload"),
                        ],
                        max_length=256,
                        unique=True,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="posttag",
            name="categories",
            field=models.ManyToManyField(to="posts.posttagcategory"),
        ),
    ]
