# Generated by Django 5.2.11 on 2026-03-08 04:45

import django.contrib.postgres.fields
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0030_posttagcategory_posttag_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttag",
            name="aliases",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=models.CharField(max_length=255), blank=True, default=list, size=None
            ),
        ),
        migrations.AlterField(
            model_name="posttagcategory",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("area", "Area"),
                    ("skill", "Skill"),
                    ("education", "Education"),
                    ("experience", "Experience"),
                    ("workload", "Workload"),
                    ("country", "Country"),
                    ("city", "City"),
                ],
                max_length=256,
                unique=True,
            ),
        ),
    ]
