# Generated by Django 5.2.11 on 2026-03-10 06:43

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0031_posttag_aliases_alter_posttagcategory_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="posttagcategory",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("area", "Area"),
                    ("skill", "Skill"),
                    ("education", "Education"),
                    ("experience", "Experience"),
                    ("workload", "Workload"),
                    ("country", "Country"),
                    ("city", "City"),
                    ("visa_sponsorship", "Visasponsorship"),
                ],
                max_length=256,
                unique=True,
            ),
        ),
    ]
