# Generated by Django 5.2.11 on 2026-03-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0032_alter_posttagcategory_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttag",
            name="is_always_indexed_by_algolia",
            field=models.BooleanField(
                default=False,
                help_text="Enabling makes it visible Algolia filters, even when no model (Job, Profile) have ever matched it. Be careful, as it then falls on you to cleanup every outdated tag with this flag in the admin panel.",
            ),
        ),
    ]
