# Generated by Django 6.0.5 on 2026-05-27 01:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0035_rename_career_capital_tag"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="read_by_users",
            field=models.ManyToManyField(
                blank=True,
                help_text="Marked as 'read' by clicking on vertical line in CommentThread",
                related_name="posts_read",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
