# Generated by Django 5.2.7 on 2025-10-19 19:17

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("posts", "0018_alter_historicalpost_source_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PostSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "domain",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[("hackernews", "Hackernews")],
                        default=None,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("id_external", models.CharField(blank=True)),
                (
                    "rank",
                    models.PositiveIntegerField(
                        blank=True, help_text="Eg from HN Firebase API", null=True
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255)),
                (
                    "url_of_source",
                    models.CharField(
                        blank=True, help_text="Eg a blog url imported from HN", max_length=255
                    ),
                ),
                (
                    "score",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="To be integrated with our reputation system",
                        null=True,
                    ),
                ),
                ("json", models.JSONField(blank=True, help_text="Raw JSON used in the import")),
                ("created_at_external", models.DateTimeField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts_source",
                        related_query_name="post_source",
                        to="posts.post",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="UserSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("id_external", models.CharField(max_length=255)),
                ("username", models.CharField(max_length=255)),
                ("score", models.PositiveIntegerField(default=0)),
                ("created_at_external", models.DateTimeField(blank=True, null=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        related_query_name="user",
                        to="importer.postsource",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
