# Generated by Django 5.2.7 on 2025-10-20 03:40

import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApiHourlyLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("HackerNews", "Hackernews"),
                            ("HackerNewsAlgolia", "Hackernewsalgolia"),
                        ],
                        max_length=17,
                    ),
                ),
                ("count_current", models.PositiveIntegerField(default=0)),
                ("count_max_per_hour", models.PositiveIntegerField(default=10000)),
                ("query_at_first", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
