# Generated by Django 5.2.7 on 2025-10-20 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0002_apihourlylimit"),
        ("posts", "0020_alter_historicalpost_slug_alter_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsource",
            name="post",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="posts_source",
                related_query_name="post_source",
                to="posts.post",
            ),
        ),
    ]
