# Generated by Django 5.2.7 on 2025-11-03 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0004_alter_postsource_post"),
        ("posts", "0021_historicalpost_parent_root_post_collapsed_by_users_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsource",
            name="post",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_source",
                related_query_name="post_source",
                to="posts.post",
            ),
        ),
    ]
