# Generated by Django 5.2.8 on 2025-11-18 04:04

import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0005_alter_postsource_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="usersource",
            name="about",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="usersource",
            name="json",
            field=models.JSONField(blank=True, default={}, help_text="Raw JSON from the import"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="apihourlylimit",
            name="source",
            field=django_choices_field.fields.TextChoicesField(
                choices=[("HackerNews", "Hackernews"), ("Algolia", "Algolia")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="postsource",
            name="json",
            field=models.JSONField(blank=True, help_text="Raw JSON from the import"),
        ),
        migrations.AlterField(
            model_name="postsource",
            name="rank",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="As HackerNews hides the Comment scores, we derive it from the Firebase API response order and save here",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="usersource",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="authors",
                related_query_name="author",
                to="importer.postsource",
            ),
        ),
    ]
