# Generated by Django 5.2.8 on 2025-11-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0006_usersource_about_usersource_json_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersource",
            name="score",
            field=models.IntegerField(default=0),
        ),
    ]
