# Generated by Django 5.2.8 on 2025-11-18 06:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0007_alter_usersource_score"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usersource",
            name="post",
        ),
        migrations.AddField(
            model_name="postsource",
            name="user_source",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="posts",
                related_query_name="post",
                to="importer.usersource",
            ),
        ),
    ]
