# Generated by Django 5.2.8 on 2025-11-28 00:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0008_remove_usersource_post_postsource_user_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="apihourlylimit",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="postsource",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="usersource",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
