# Generated by Django 5.2.9 on 2026-01-09 01:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0009_alter_apihourlylimit_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="postsource",
            name="rank",
            field=models.PositiveIntegerField(
                blank=True,
                help_text="As HackerNews hides the Comment scores, we derive it from the Firebase API response order and save in .rank",
                null=True,
            ),
        ),
    ]
