# Generated by Django 5.2.9 on 2026-01-14 04:23

import uuid

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0010_alter_postsource_rank"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImportTaskCronAuthToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("token", models.CharField(default=uuid.uuid4, max_length=1024)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
