# Generated by Django 5.2.9 on 2026-01-15 02:25

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0011_importtaskcronauthtoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="postsource",
            name="source_html_meta",
            field=models.TextField(blank=True),
        ),
    ]
