# Generated by Django 5.2.9 on 2026-01-15 04:03

import datetime

from django.db import migrations
from django.db import models


def migrate_query_at_first_to_query_date_and_hour(apps, schema_editor):
    ApiHourlyLimit = apps.get_model("importer", "ApiHourlyLimit")
    for limit in ApiHourlyLimit.objects.all():
        limit.query_date = limit.query_at_first.date()
        limit.query_hour = limit.query_at_first.hour
        limit.save()


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0012_postsource_source_html_meta"),
    ]

    operations = [
        migrations.AddField(
            model_name="apihourlylimit",
            name="query_date",
            field=models.DateField(
                default=datetime.datetime(2026, 1, 15, 4, 2, 27, 388853, tzinfo=datetime.UTC)
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="apihourlylimit",
            name="query_hour",
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunPython(
            migrate_query_at_first_to_query_date_and_hour,
            reverse_code=migrations.RunPython.noop,
        ),
        # migrations.AddConstraint(
        #     model_name="apihourlylimit",
        #     constraint=models.UniqueConstraint(
        #         fields=("source", "query_date", "query_hour"), name="api_limit_unique_per_hour"
        #     ),
        # ),
    ]
