# Generated by Django 6.0.5 on 2026-05-27 01:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("importer", "0014_merge_apihourlylimit_duplicates_add_constraint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="usersource",
            name="followed_by_users",
            field=models.ManyToManyField(
                blank=True,
                related_name="users_followed_sources",
                related_query_name="users_followed_source",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
