name: Lint

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/Dockerfile"
      - "devops/coder/**"
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
    branches:
      - master

jobs:
  lint:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read

    env:
      # todo ! fix: run for both both VITE_SITE="" and "pg"
      VITE_SITE: pg

    steps:
      - name: Run Git checkout
        uses: actions/checkout@v6

      - name: Setup Mise
        uses: jdx/mise-action@v3

      - run: mise run install-deps:client

      - run: mise run format
      - run: mise run lint
