name: Pytest

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/*.md"
      - "**/Dockerfile"
      - "devops/coder/**"
  pull_request:
    types: [ opened, synchronize, ready_for_review ]
    branches:
      - master

jobs:
  pytest:
    if: github.event.pull_request.draft == false

    runs-on: ubuntu-latest
    environment: test
    permissions:
      contents: read

    services:
      postgres:
        image: postgres:18-alpine
        ports:
          - 5432:5432
        env:
          POSTGRES_DB: neuronhub
          POSTGRES_USER: neuronhub
          POSTGRES_PASSWORD: neuronhub
        options: >-
          --health-cmd "pg_isready --username neuronhub"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
      s3:
        image: adobe/s3mock:latest
        ports:
          - 9090:9090
        env:
          initialBuckets: media
    env:
      DB_HOST: localhost
      AWS_S3_ENDPOINT_URL: http://localhost:9090

    steps:
      - name: Run Git checkout
        uses: actions/checkout@v6

      - name: Setup Mise
        uses: jdx/mise-action@v3

      - name: Setup uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true
          working-directory: ${{ github.workspace }}/server

      - run: mise run install-deps:server

      - name: Pytest
        run: mise run pytest
        env:
          IS_POSTGRES_EXTERNAL: true
          # empty by default
          USER: runner
