// todo ! feat: backend should expose full location lists (mirroring Airtable) via API
export const locationRemoteNames = [
  "Remote, Global",
  "Remote, USA",
  "Remote, UK",
  "Remote, Europe",
];

export const locationCountryNames = [
  "Afghanistan",
  "Albania",
  "Algeria",
  "Angola",
  "Argentina",
  "Armenia",
  "Australia",
  "Austria",
  "Bahamas",
  "Bangladesh",
  "Barbados",
  "Belgium",
  "Belize",
  "Benin",
  "Bolivia",
  "Bosnia",
  "Bosnia and Herzegovina",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Burkina Faso",
  "Burundi",
  "Cambodia",
  "Cameroon",
  "Canada",
  "Central African Republic",
  "Chad",
  "Chile",
  "China",
  "Colombia",
  "Costa Rica",
  "Côte d'Ivoire",
  "Czechia",
  "Democratic Republic of the Congo",
  "Denmark",
  "Djibouti",
  "Dominican Republic",
  "Ecuador",
  "Egypt",
  "El Salvador",
  "Equatorial Guinea",
  "Estonia",
  "Eswatini",
  "Ethiopia",
  "Fiji",
  "Finland",
  "France",
  "Gaza",
  "Germany",
  "Ghana",
  "Greece",
  "Guatemala",
  "Guinea",
  "Guinea-Bissau",
  "Guyana",
  "Haiti",
  "Honduras",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "India",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kazakhstan",
  "Kenya",
  "Kiribati",
  "Laos",
  "Lebanon",
  "Lesotho",
  "Liberia",
  "Libya",
  "Lithuania",
  "Luxembourg",
  "Madagascar",
  "Malawi",
  "Malaysia",
  "Mali",
  "Marshall Islands",
  "Mauritania",
  "Mauritius",
  "Mexico",
  "Mongolia",
  "Morocco",
  "Mozambique",
  "Multiple Locations: Africa",
  "Multiple Locations: APAC Region",
  "Multiple Locations: Europe",
  "Multiple Locations: Latin America",
  "Myanmar",
  "Namibia",
  "Nepal",
  "Netherlands",
  "New Zealand",
  "Niger",
  "Nigeria",
  "Norway",
  "Pakistan",
  "Palestine",
  "Panama",
  "Papua New Guinea",
  "Paraguay",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Romania",
  "Rwanda",
  "Saint Lucia",
  "Saudi Arabia",
  "Senegal",
  "Serbia",
  "Sierra Leone",
  "Singapore",
  "Slovakia",
  "Somalia",
  "South Africa",
  "South Korea",
  "South Sudan",
  "Spain",
  "Sri Lanka",
  "Sudan",
  "Suriname",
  "Sweden",
  "Switzerland",
  "Syria",
  "Taiwan",
  "Tajikistan",
  "Tanzania",
  "Thailand",
  "The Gambia",
  "Timor-Leste",
  "Togo",
  "Tonga",
  "Trinidad and Tobago",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "United Kingdom",
  "United States",
  "Uruguay",
  "Uzbekistan",
  "Venezuela",
  "Vietnam",
  "Zambia",
  "Zimbabwe",
];

export const locationCityNames = [
  "Abidjan",
  "Abuja",
  "Accra",
  "Addis Ababa",
  "Allschwil",
  "Amdjarass",
  "Amman",
  "Amsterdam",
  "Andhra Pradesh",
  "Antananarivo",
  "Arlington VA",
  "Atlanta GA",
  "Atlantic City NJ",
  "Austin TX",
  "Baltimore MD",
  "Bamako",
  "Bangalore",
  "Bangkok",
  "Bangui",
  "Banjul",
  "Barcelona",
  "Basel",
  "Beijing",
  "Beirut",
  "Bengaluru",
  "Berkeley CA",
  "Berlin",
  "Bern",
  "Bethesda MD",
  "Bhopal",
  "Bilthoven",
  "Birmingham",
  "Birnin Kebbi",
  "Bitkine",
  "Bocaranga",
  "Bogotá",
  "Bonn",
  "Boston MA",
  "Boulder CO",
  "Brisbane",
  "Brisbane CA",
  "Brooklyn NY",
  "Broomfield CO",
  "Brussels",
  "Bryan TX",
  "Budapest",
  "Buenos Aires",
  "Buhumuza",
  "Bujumbura",
  "Bukavu",
  "Burunga",
  "Cairo",
  "Cambridge",
  "Cambridge MA",
  "Cape Town",
  "Cardiff",
  "Chicago IL",
  "Christchurch",
  "Coimbatore",
  "Conakry",
  "Copenhagen",
  "Cotonou",
  "Covina CA",
  "Dakar",
  "Dar es Salaam",
  "Darlington",
  "Decatur GA",
  "Delhi",
  "Dhaka",
  "Dodoma",
  "Dublin",
  "Durham NC",
  "Edinburgh",
  "Edmonton",
  "Emeryville CA",
  "Entebbe",
  "Florence",
  "Fort Lupton CO",
  "Fort-de-France",
  "Freetown",
  "Gaithersburg MD",
  "Gebze",
  "Geneva",
  "Ghent",
  "Gicumbi",
  "Gitega",
  "Grenoble",
  "Guatemala City",
  "Gujarat",
  "Gütersloh",
  "Guwahati",
  "Hamburg",
  "Hanoi",
  "Harare",
  "Haywards Heath",
  "Heidelberg",
  "Himachal Pradesh",
  "Hinxton",
  "Ho Chi Minh",
  "Houston TX",
  "Hpa-An",
  "Huehuetenango",
  "Hyderabad",
  "Islamabad",
  "Jabi",
  "Jakarta",
  "Johannesburg",
  "Juba",
  "Kabul",
  "Kadiogo",
  "Kaduna",
  "Kambia",
  "Kampala",
  "Karachi",
  "Karnataka",
  "Karongi",
  "Kathmandu",
  "Katsina",
  "Kebbi",
  "Kigali",
  "Kinshasa",
  "Kirkland WA",
  "Koch",
  "Kolkata",
  "Kyiv",
  "Lagos",
  "Lahore",
  "Lilongwe",
  "Lincoln NE",
  "Lisbon",
  "Livermore CA",
  "London",
  "Los Angeles CA",
  "Lucknow",
  "Lusaka",
  "Maharashtra",
  "Mainz",
  "Makati City",
  "Manakara",
  "Manchester",
  "Manila",
  "Maputo",
  "Maryland MD",
  "Mbale",
  "Mbarara",
  "Mekelle",
  "Melbourne",
  "Milton Park",
  "Mogadishu",
  "Moka",
  "Monguno",
  "Monrovia",
  "Monterey CA",
  "Montgomery County MD",
  "Montpellier",
  "Montreal",
  "Montserrado",
  "Mountain View CA",
  "Mumbai",
  "Munich",
  "N'Djamena",
  "Nairobi",
  "Nalanda",
  "Nashik",
  "New Delhi",
  "New Haven CT",
  "New York",
  "New York NY",
  "Ngororero",
  "Niamey",
  "Niger State",
  "Norwich",
  "Nyabihu",
  "Oakland CA",
  "Opfikon",
  "Oslo",
  "Ottawa",
  "Ouagadougou",
  "Oxford",
  "Palo Alto CA",
  "Panama City FL",
  "Paris",
  "Patna",
  "Phnom Penh",
  "Pittsburgh PA",
  "Port Sudan",
  "Port-au-Prince",
  "Prague",
  "Pretoria",
  "Princeton NJ",
  "Provence",
  "Pune",
  "Quebec",
  "Quezon City",
  "Rabat",
  "Rajasthan",
  "Ramat Gan",
  "Ranchi",
  "Remscheid",
  "Rio de Janeiro",
  "Rome",
  "Rotterdam",
  "Sacramento CA",
  "Salt Lake City UT",
  "Sambalpur",
  "San Diego CA",
  "San Francisco CA",
  "San Jose CA",
  "San Mateo CA",
  "Santa Monica CA",
  "São Paulo",
  "Seattle WA",
  "Sejong",
  "Seoul",
  "Shanghai",
  "Sheffield",
  "Silver Spring MD",
  "Singapore",
  "Sokoto",
  "Somerville MA",
  "Steyning",
  "Stockholm",
  "Stuttgart",
  "Sydney",
  "Tallinn",
  "Tel Aviv",
  "Thane",
  "Tharparkar",
  "The Hague",
  "Thiès",
  "Tokyo",
  "Toronto",
  "Tripoli",
  "Tübingen",
  "Ujjain",
  "Uppsala",
  "Utrecht",
  "Uttar Pradesh",
  "Vancouver WA",
  "Vienna",
  "Vijayawada",
  "Vilnius",
  "Visakhapatnam",
  "Warsaw",
  "Washington D.C.",
  "West Sussex",
  "Wolverhampton",
  "Yangon",
  "Yaoundé",
  "Zurich",
];
