# Generated by Django 5.2.4 on 2025-08-14 22:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of this User (Alias), if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="aliases",
                related_query_name="alias",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
