# Generated by Django 5.2.12 on 2026-04-12 23:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_owner"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAnon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email_hash", models.CharField(max_length=128, unique=True)),
                ("anon_name", models.CharField(max_length=128, unique=True)),
            ],
        ),
    ]
