# Generated by Django 5.2 on 2025-04-14 20:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def gen_uuid(apps, schema_editor):
    User = apps.get_model("users", "User")
    for row in User.objects.all():
        row.id_uuid = uuid.uuid4()
        row.save()


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_username"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=False),
        ),
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
            model_name="user",
            name="id_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                help_text="Owner of this User (Alias), if any",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
